import Foundation

enum AppLanguage: String {
    case es, en, fr, de, it, pt, ja, zh, ko, ru

    static let current: AppLanguage = {
        for raw in Locale.preferredLanguages {
            let code = raw.lowercased()
            if code.hasPrefix("es") { return .es }
            if code.hasPrefix("en") { return .en }
            if code.hasPrefix("fr") { return .fr }
            if code.hasPrefix("de") { return .de }
            if code.hasPrefix("it") { return .it }
            if code.hasPrefix("pt") { return .pt }
            if code.hasPrefix("ja") { return .ja }
            if code.hasPrefix("zh") { return .zh }
            if code.hasPrefix("ko") { return .ko }
            if code.hasPrefix("ru") { return .ru }
        }
        return .en
    }()
}

enum L {
    static func t(_ es: String, _ en: String) -> String {
        switch AppLanguage.current {
        case .es: return es
        case .en: return en
        default: return Translations.tables[AppLanguage.current]?[es] ?? en
        }
    }
}

enum Translations {
    static let tables: [AppLanguage: [String: String]] = [
        .fr: fr, .de: de, .it: it, .pt: pt, .ja: ja, .zh: zh, .ko: ko, .ru: ru,
    ]

    private static let fr: [String: String] = [
        "%d turnos en 30 días": "%d tours sur 30 jours",
        "Abrir AI Usage": "Ouvrir AI Usage",
        "Abrir al iniciar sesión en el Mac": "Ouvrir à l'ouverture de session",
        "Abrir navegador para autorizar": "Ouvrir le navigateur pour autoriser",
        "Abrir panel": "Ouvrir le panneau",
        "Actualizado a las %@": "Mis à jour à %@",
        "Actualizar ahora": "Actualiser maintenant",
        "Ajustes": "Réglages",
        "Ajustes…": "Réglages…",
        "Apps · semana": "Apps · semaine",
        "Automático (Claude primero)": "Automatique (Claude d'abord)",
        "Autoriza en el navegador y pega abajo el código que se muestra.": "Autorisez dans le navigateur et collez ci-dessous le code affiché.",
        "Autorizado": "Autorisé",
        "Bloque actual (5 h)": "Bloc actuel (5 h)",
        "Caché": "Cache",
        "Cancelar": "Annuler",
        "Cerrar sesión propia": "Se déconnecter",
        "Cerrar": "Fermer",
        "Codex CLI detectado": "Codex CLI détecté",
        "Codex CLI no encontrado": "Codex CLI introuvable",
        "Conectar con %@": "Se connecter à %@",
        "Conectar": "Connecter",
        "Consumido": "Consommé",
        "Copiar enlace de autorización": "Copier le lien d'autorisation",
        "Coste de hoy (total)": "Coût du jour (total)",
        "Coste": "Coût",
        "Créditos": "Crédits",
        "Cuenta": "Compte",
        "Datos locales": "Données locales",
        "Entrada": "Entrée",
        "Esperando autorización…": "En attente d'autorisation…",
        "Esperando la autorización del navegador…": "En attente de l'autorisation du navigateur…",
        "Hoy": "Aujourd'hui",
        "Ilimitados": "Illimités",
        "Iniciar sesión con %@": "Se connecter avec %@",
        "Iniciar sesión con Claude…": "Se connecter avec Claude…",
        "Iniciar sesión con OpenAI…": "Se connecter avec OpenAI…",
        "Intercambiando el código por la sesión…": "Échange du code contre la session…",
        "JSON inesperado": "JSON inattendu",
        "La barra de menús muestra": "La barre de menus affiche",
        "La sesión se guarda en un ítem propio del llavero. La app no lee las credenciales de Claude Code, así que macOS no pide permisos de acceso.": "La session est enregistrée dans un élément de trousseau propre à l'app. L'app ne lit jamais les identifiants de Claude Code, macOS ne demandera donc aucun accès.",
        "Leyendo datos de uso…": "Lecture des données d'utilisation…",
        "Los tokens salen de las sesiones locales de Codex CLI (~/.codex/sessions). Los límites del plan se consultan en vivo a chatgpt.com con tu sesión de OpenAI.": "Les tokens proviennent des sessions locales de Codex CLI (~/.codex/sessions). Les limites du forfait sont consultées en direct sur chatgpt.com avec votre session OpenAI.",
        "Límite alcanzado: %@": "Limite atteinte : %@",
        "Límite de gasto": "Plafond de dépenses",
        "Límite": "Limite",
        "Límites del plan": "Limites du forfait",
        "Límites: %@": "Limites : %@",
        "Mensajes": "Messages",
        "Modelo": "Modèle",
        "Mostrar límites como": "Afficher les limites en",
        "No se han encontrado sesiones de Codex CLI en ~/.codex.": "Aucune session Codex CLI trouvée dans ~/.codex.",
        "Opus · semana": "Opus · semaine",
        "Por modelo (últimos 30 días)": "Par modèle (30 derniers jours)",
        "Reintentar": "Réessayer",
        "Restante": "Restant",
        "Restaurar orden por defecto": "Restaurer l'ordre par défaut",
        "Salida": "Sortie",
        "Salir completamente": "Quitter complètement",
        "Salir": "Quitter",
        "Se abrirá el navegador para autorizar el acceso con tu cuenta de Claude (el mismo flujo que usa Claude Code). Al aceptar, la app recibirá la autorización automáticamente.": "Votre navigateur s'ouvrira pour autoriser l'accès avec votre compte Claude (le même flux que Claude Code). Une fois accepté, l'app recevra automatiquement l'autorisation.",
        "Se abrirá el navegador para autorizar el acceso con tu cuenta de OpenAI/ChatGPT (el mismo flujo que usa Codex CLI). Al aceptar, la app recibirá la autorización automáticamente.": "Votre navigateur s'ouvrira pour autoriser l'accès avec votre compte OpenAI/ChatGPT (le même flux que Codex CLI). Une fois accepté, l'app recevra automatiquement l'autorisation.",
        "Se reinicia el %@ a las %@": "Se réinitialise le %@ à %@",
        "Se reinicia en %@ (%@)": "Se réinitialise dans %@ (%@)",
        "Secciones del menú": "Sections du menu",
        "Semana": "Semaine",
        "Sesión (5 h)": "Session (5 h)",
        "Sesión iniciada correctamente": "Connexion réussie",
        "Sesión": "Session",
        "Sonnet · semana": "Sonnet · semaine",
        "Uso extra (mes)": "Usage supplémentaire (mois)",
        "Visualización": "Affichage",
        "Ya puedes cerrar esta pestaña y volver a AI Usage.": "Vous pouvez fermer cet onglet et revenir à AI Usage.",
        "auth.json de Codex CLI": "auth.json de Codex CLI",
        "caché": "cache",
        "créditos de tu usuario del workspace agotados": "crédits de votre utilisateur du workspace épuisés",
        "créditos del propietario del workspace agotados": "crédits du propriétaire du workspace épuisés",
        "código#estado": "code#état",
        "de": "sur",
        "días": "jours",
        "el puerto %@ está ocupado — ciérralo (p. ej. un «codex login» a medias) y reintenta": "le port %@ est occupé — fermez ce qui l'utilise (p. ex. un « codex login » en cours) et réessayez",
        "entrada": "entrée",
        "libre": "libre",
        "límite de uso alcanzado": "limite d'utilisation atteinte",
        "límite de uso de tu usuario alcanzado": "limite d'utilisation de votre utilisateur atteinte",
        "límite de uso del workspace alcanzado": "limite d'utilisation du workspace atteinte",
        "límite": "limite",
        "mensajes": "messages",
        "propia de la app (caduca %@)": "propre à l'app (expire %@)",
        "propia de la app (renovación automática)": "propre à l'app (renouvellement auto)",
        "propia de la app": "propre à l'app",
        "respuesta no válida": "réponse invalide",
        "salida": "sortie",
        "sesión caducada — vuelve a iniciar sesión": "session expirée — reconnectez-vous",
        "sesión no autorizada — vuelve a iniciar sesión": "session non autorisée — reconnectez-vous",
        "sin actividad reciente": "aucune activité récente",
        "sin datos de límites": "pas de données de limites",
        "sin sesión — conéctate con tu cuenta de Claude": "pas de session — connectez-vous avec votre compte Claude",
        "sin sesión — conéctate con tu cuenta de OpenAI": "pas de session — connectez-vous avec votre compte OpenAI",
        "sin sesión": "pas de session",
        "termina a las %@ · quedan %@": "se termine à %@ · %@ restants",
        "termina a las %@": "se termine à %@",
        "tope de gasto alcanzado": "plafond de dépenses atteint",
        "usado": "utilisé",
        "¿No vuelve solo? Pega el código manualmente": "Ça ne revient pas tout seul ? Collez le code manuellement",
        "Últimos 14 días": "14 derniers jours",
        "Últimos 30 días": "30 derniers jours",
        "Últimos 7 días (total)": "7 derniers jours (total)",
        "Últimos 7 días": "7 derniers jours",
    ]

    private static let de: [String: String] = [
        "%d turnos en 30 días": "%d Turns in 30 Tagen",
        "Abrir AI Usage": "AI Usage öffnen",
        "Abrir al iniciar sesión en el Mac": "Beim Anmelden öffnen",
        "Abrir navegador para autorizar": "Browser zum Autorisieren öffnen",
        "Abrir panel": "Übersicht öffnen",
        "Actualizado a las %@": "Aktualisiert um %@",
        "Actualizar ahora": "Jetzt aktualisieren",
        "Ajustes": "Einstellungen",
        "Ajustes…": "Einstellungen…",
        "Apps · semana": "Apps · Woche",
        "Automático (Claude primero)": "Automatisch (Claude zuerst)",
        "Autoriza en el navegador y pega abajo el código que se muestra.": "Autorisiere im Browser und füge unten den angezeigten Code ein.",
        "Autorizado": "Autorisiert",
        "Bloque actual (5 h)": "Aktueller Block (5 Std.)",
        "Caché": "Cache",
        "Cancelar": "Abbrechen",
        "Cerrar sesión propia": "Abmelden",
        "Cerrar": "Schließen",
        "Codex CLI detectado": "Codex CLI erkannt",
        "Codex CLI no encontrado": "Codex CLI nicht gefunden",
        "Conectar con %@": "Mit %@ verbinden",
        "Conectar": "Verbinden",
        "Consumido": "Verbraucht",
        "Copiar enlace de autorización": "Autorisierungslink kopieren",
        "Coste de hoy (total)": "Kosten heute (gesamt)",
        "Coste": "Kosten",
        "Créditos": "Guthaben",
        "Cuenta": "Konto",
        "Datos locales": "Lokale Daten",
        "Entrada": "Eingabe",
        "Esperando autorización…": "Warte auf Autorisierung…",
        "Esperando la autorización del navegador…": "Warte auf die Autorisierung im Browser…",
        "Hoy": "Heute",
        "Ilimitados": "Unbegrenzt",
        "Iniciar sesión con %@": "Mit %@ anmelden",
        "Iniciar sesión con Claude…": "Mit Claude anmelden…",
        "Iniciar sesión con OpenAI…": "Mit OpenAI anmelden…",
        "Intercambiando el código por la sesión…": "Code wird gegen Sitzung getauscht…",
        "JSON inesperado": "Unerwartetes JSON",
        "La barra de menús muestra": "Menüleiste zeigt",
        "La sesión se guarda en un ítem propio del llavero. La app no lee las credenciales de Claude Code, así que macOS no pide permisos de acceso.": "Die Sitzung wird in einem eigenen Schlüsselbund-Eintrag der App gespeichert. Die App liest nie die Zugangsdaten von Claude Code, daher fragt macOS nicht nach Zugriff.",
        "Leyendo datos de uso…": "Nutzungsdaten werden gelesen…",
        "Los tokens salen de las sesiones locales de Codex CLI (~/.codex/sessions). Los límites del plan se consultan en vivo a chatgpt.com con tu sesión de OpenAI.": "Die Token stammen aus den lokalen Codex-CLI-Sitzungen (~/.codex/sessions). Die Plan-Limits werden live über chatgpt.com mit deiner OpenAI-Sitzung abgefragt.",
        "Límite alcanzado: %@": "Limit erreicht: %@",
        "Límite de gasto": "Ausgabenlimit",
        "Límite": "Limit",
        "Límites del plan": "Plan-Limits",
        "Límites: %@": "Limits: %@",
        "Mensajes": "Nachrichten",
        "Modelo": "Modell",
        "Mostrar límites como": "Limits anzeigen als",
        "No se han encontrado sesiones de Codex CLI en ~/.codex.": "Keine Codex-CLI-Sitzungen in ~/.codex gefunden.",
        "Opus · semana": "Opus · Woche",
        "Por modelo (últimos 30 días)": "Nach Modell (letzte 30 Tage)",
        "Reintentar": "Erneut versuchen",
        "Restante": "Verbleibend",
        "Restaurar orden por defecto": "Standardreihenfolge wiederherstellen",
        "Salida": "Ausgabe",
        "Salir completamente": "Vollständig beenden",
        "Salir": "Beenden",
        "Se abrirá el navegador para autorizar el acceso con tu cuenta de Claude (el mismo flujo que usa Claude Code). Al aceptar, la app recibirá la autorización automáticamente.": "Der Browser öffnet sich, um den Zugriff mit deinem Claude-Konto zu autorisieren (derselbe Ablauf wie bei Claude Code). Nach der Bestätigung erhält die App die Autorisierung automatisch.",
        "Se abrirá el navegador para autorizar el acceso con tu cuenta de OpenAI/ChatGPT (el mismo flujo que usa Codex CLI). Al aceptar, la app recibirá la autorización automáticamente.": "Der Browser öffnet sich, um den Zugriff mit deinem OpenAI/ChatGPT-Konto zu autorisieren (derselbe Ablauf wie bei Codex CLI). Nach der Bestätigung erhält die App die Autorisierung automatisch.",
        "Se reinicia el %@ a las %@": "Setzt sich am %@ um %@ zurück",
        "Se reinicia en %@ (%@)": "Setzt sich in %@ zurück (%@)",
        "Secciones del menú": "Menü-Abschnitte",
        "Semana": "Woche",
        "Sesión (5 h)": "Sitzung (5 Std.)",
        "Sesión iniciada correctamente": "Erfolgreich angemeldet",
        "Sesión": "Sitzung",
        "Sonnet · semana": "Sonnet · Woche",
        "Uso extra (mes)": "Zusätzliche Nutzung (Monat)",
        "Visualización": "Darstellung",
        "Ya puedes cerrar esta pestaña y volver a AI Usage.": "Du kannst diesen Tab schließen und zu AI Usage zurückkehren.",
        "auth.json de Codex CLI": "auth.json von Codex CLI",
        "caché": "Cache",
        "créditos de tu usuario del workspace agotados": "Guthaben deines Workspace-Nutzers aufgebraucht",
        "créditos del propietario del workspace agotados": "Guthaben des Workspace-Inhabers aufgebraucht",
        "código#estado": "Code#Status",
        "de": "von",
        "días": "Tage",
        "el puerto %@ está ocupado — ciérralo (p. ej. un «codex login» a medias) y reintenta": "Port %@ ist belegt — schließe, was ihn belegt (z. B. ein laufendes „codex login“), und versuche es erneut",
        "entrada": "Eingabe",
        "libre": "frei",
        "límite de uso alcanzado": "Nutzungslimit erreicht",
        "límite de uso de tu usuario alcanzado": "Nutzungslimit deines Nutzers erreicht",
        "límite de uso del workspace alcanzado": "Nutzungslimit des Workspace erreicht",
        "límite": "Limit",
        "mensajes": "Nachrichten",
        "propia de la app (caduca %@)": "App-eigen (läuft %@ ab)",
        "propia de la app (renovación automática)": "App-eigen (automatische Verlängerung)",
        "propia de la app": "App-eigen",
        "respuesta no válida": "ungültige Antwort",
        "salida": "Ausgabe",
        "sesión caducada — vuelve a iniciar sesión": "Sitzung abgelaufen — melde dich erneut an",
        "sesión no autorizada — vuelve a iniciar sesión": "Sitzung nicht autorisiert — melde dich erneut an",
        "sin actividad reciente": "keine aktuelle Aktivität",
        "sin datos de límites": "keine Limit-Daten",
        "sin sesión — conéctate con tu cuenta de Claude": "keine Sitzung — melde dich mit deinem Claude-Konto an",
        "sin sesión — conéctate con tu cuenta de OpenAI": "keine Sitzung — melde dich mit deinem OpenAI-Konto an",
        "sin sesión": "keine Sitzung",
        "termina a las %@ · quedan %@": "endet um %@ · noch %@",
        "termina a las %@": "endet um %@",
        "tope de gasto alcanzado": "Ausgabenlimit erreicht",
        "usado": "belegt",
        "¿No vuelve solo? Pega el código manualmente": "Kommt nichts zurück? Füge den Code manuell ein",
        "Últimos 14 días": "Letzte 14 Tage",
        "Últimos 30 días": "Letzte 30 Tage",
        "Últimos 7 días (total)": "Letzte 7 Tage (gesamt)",
        "Últimos 7 días": "Letzte 7 Tage",
    ]

    private static let it: [String: String] = [
        "%d turnos en 30 días": "%d turni in 30 giorni",
        "Abrir AI Usage": "Apri AI Usage",
        "Abrir al iniciar sesión en el Mac": "Apri all'accesso",
        "Abrir navegador para autorizar": "Apri il browser per autorizzare",
        "Abrir panel": "Apri pannello",
        "Actualizado a las %@": "Aggiornato alle %@",
        "Actualizar ahora": "Aggiorna ora",
        "Ajustes": "Impostazioni",
        "Ajustes…": "Impostazioni…",
        "Apps · semana": "App · settimana",
        "Automático (Claude primero)": "Automatico (prima Claude)",
        "Autoriza en el navegador y pega abajo el código que se muestra.": "Autorizza nel browser e incolla qui sotto il codice mostrato.",
        "Autorizado": "Autorizzato",
        "Bloque actual (5 h)": "Blocco attuale (5 h)",
        "Caché": "Cache",
        "Cancelar": "Annulla",
        "Cerrar sesión propia": "Disconnetti",
        "Cerrar": "Chiudi",
        "Codex CLI detectado": "Codex CLI rilevato",
        "Codex CLI no encontrado": "Codex CLI non trovato",
        "Conectar con %@": "Connetti a %@",
        "Conectar": "Connetti",
        "Consumido": "Consumato",
        "Copiar enlace de autorización": "Copia link di autorizzazione",
        "Coste de hoy (total)": "Costo di oggi (totale)",
        "Coste": "Costo",
        "Créditos": "Crediti",
        "Cuenta": "Account",
        "Datos locales": "Dati locali",
        "Entrada": "Input",
        "Esperando autorización…": "In attesa di autorizzazione…",
        "Esperando la autorización del navegador…": "In attesa dell'autorizzazione dal browser…",
        "Hoy": "Oggi",
        "Ilimitados": "Illimitati",
        "Iniciar sesión con %@": "Accedi con %@",
        "Iniciar sesión con Claude…": "Accedi con Claude…",
        "Iniciar sesión con OpenAI…": "Accedi con OpenAI…",
        "Intercambiando el código por la sesión…": "Scambio del codice con la sessione…",
        "JSON inesperado": "JSON imprevisto",
        "La barra de menús muestra": "La barra dei menu mostra",
        "La sesión se guarda en un ítem propio del llavero. La app no lee las credenciales de Claude Code, así que macOS no pide permisos de acceso.": "La sessione è salvata in un elemento del portachiavi dell'app. L'app non legge mai le credenziali di Claude Code, quindi macOS non chiederà l'accesso.",
        "Leyendo datos de uso…": "Lettura dei dati di utilizzo…",
        "Los tokens salen de las sesiones locales de Codex CLI (~/.codex/sessions). Los límites del plan se consultan en vivo a chatgpt.com con tu sesión de OpenAI.": "I token provengono dalle sessioni locali di Codex CLI (~/.codex/sessions). I limiti del piano vengono letti in tempo reale da chatgpt.com con la tua sessione OpenAI.",
        "Límite alcanzado: %@": "Limite raggiunto: %@",
        "Límite de gasto": "Limite di spesa",
        "Límite": "Limite",
        "Límites del plan": "Limiti del piano",
        "Límites: %@": "Limiti: %@",
        "Mensajes": "Messaggi",
        "Modelo": "Modello",
        "Mostrar límites como": "Mostra i limiti come",
        "No se han encontrado sesiones de Codex CLI en ~/.codex.": "Nessuna sessione Codex CLI trovata in ~/.codex.",
        "Opus · semana": "Opus · settimana",
        "Por modelo (últimos 30 días)": "Per modello (ultimi 30 giorni)",
        "Reintentar": "Riprova",
        "Restante": "Rimanente",
        "Restaurar orden por defecto": "Ripristina ordine predefinito",
        "Salida": "Output",
        "Salir completamente": "Esci completamente",
        "Salir": "Esci",
        "Se abrirá el navegador para autorizar el acceso con tu cuenta de Claude (el mismo flujo que usa Claude Code). Al aceptar, la app recibirá la autorización automáticamente.": "Si aprirà il browser per autorizzare l'accesso con il tuo account Claude (lo stesso flusso di Claude Code). Dopo l'approvazione, l'app riceverà automaticamente l'autorizzazione.",
        "Se abrirá el navegador para autorizar el acceso con tu cuenta de OpenAI/ChatGPT (el mismo flujo que usa Codex CLI). Al aceptar, la app recibirá la autorización automáticamente.": "Si aprirà il browser per autorizzare l'accesso con il tuo account OpenAI/ChatGPT (lo stesso flusso di Codex CLI). Dopo l'approvazione, l'app riceverà automaticamente l'autorizzazione.",
        "Se reinicia el %@ a las %@": "Si azzera il %@ alle %@",
        "Se reinicia en %@ (%@)": "Si azzera tra %@ (%@)",
        "Secciones del menú": "Sezioni del menu",
        "Semana": "Settimana",
        "Sesión (5 h)": "Sessione (5 h)",
        "Sesión iniciada correctamente": "Accesso riuscito",
        "Sesión": "Sessione",
        "Sonnet · semana": "Sonnet · settimana",
        "Uso extra (mes)": "Utilizzo extra (mese)",
        "Visualización": "Visualizzazione",
        "Ya puedes cerrar esta pestaña y volver a AI Usage.": "Puoi chiudere questa scheda e tornare ad AI Usage.",
        "auth.json de Codex CLI": "auth.json di Codex CLI",
        "caché": "cache",
        "créditos de tu usuario del workspace agotados": "crediti del tuo utente del workspace esauriti",
        "créditos del propietario del workspace agotados": "crediti del proprietario del workspace esauriti",
        "código#estado": "codice#stato",
        "de": "di",
        "días": "giorni",
        "el puerto %@ está ocupado — ciérralo (p. ej. un «codex login» a medias) y reintenta": "la porta %@ è occupata — chiudi ciò che la usa (ad es. un 'codex login' in corso) e riprova",
        "entrada": "input",
        "libre": "libero",
        "límite de uso alcanzado": "limite di utilizzo raggiunto",
        "límite de uso de tu usuario alcanzado": "limite di utilizzo del tuo utente raggiunto",
        "límite de uso del workspace alcanzado": "limite di utilizzo del workspace raggiunto",
        "límite": "limite",
        "mensajes": "messaggi",
        "propia de la app (caduca %@)": "propria dell'app (scade %@)",
        "propia de la app (renovación automática)": "propria dell'app (rinnovo automatico)",
        "propia de la app": "propria dell'app",
        "respuesta no válida": "risposta non valida",
        "salida": "output",
        "sesión caducada — vuelve a iniciar sesión": "sessione scaduta — accedi di nuovo",
        "sesión no autorizada — vuelve a iniciar sesión": "sessione non autorizzata — accedi di nuovo",
        "sin actividad reciente": "nessuna attività recente",
        "sin datos de límites": "nessun dato sui limiti",
        "sin sesión — conéctate con tu cuenta de Claude": "nessuna sessione — accedi con il tuo account Claude",
        "sin sesión — conéctate con tu cuenta de OpenAI": "nessuna sessione — accedi con il tuo account OpenAI",
        "sin sesión": "nessuna sessione",
        "termina a las %@ · quedan %@": "termina alle %@ · mancano %@",
        "termina a las %@": "termina alle %@",
        "tope de gasto alcanzado": "tetto di spesa raggiunto",
        "usado": "usato",
        "¿No vuelve solo? Pega el código manualmente": "Non torna da solo? Incolla il codice manualmente",
        "Últimos 14 días": "Ultimi 14 giorni",
        "Últimos 30 días": "Ultimi 30 giorni",
        "Últimos 7 días (total)": "Ultimi 7 giorni (totale)",
        "Últimos 7 días": "Ultimi 7 giorni",
    ]

    private static let pt: [String: String] = [
        "%d turnos en 30 días": "%d turnos em 30 dias",
        "Abrir AI Usage": "Abrir AI Usage",
        "Abrir al iniciar sesión en el Mac": "Abrir ao iniciar sessão",
        "Abrir navegador para autorizar": "Abrir navegador para autorizar",
        "Abrir panel": "Abrir painel",
        "Actualizado a las %@": "Atualizado às %@",
        "Actualizar ahora": "Atualizar agora",
        "Ajustes": "Definições",
        "Ajustes…": "Definições…",
        "Apps · semana": "Apps · semana",
        "Automático (Claude primero)": "Automático (Claude primeiro)",
        "Autoriza en el navegador y pega abajo el código que se muestra.": "Autoriza no navegador e cola abaixo o código mostrado.",
        "Autorizado": "Autorizado",
        "Bloque actual (5 h)": "Bloco atual (5 h)",
        "Caché": "Cache",
        "Cancelar": "Cancelar",
        "Cerrar sesión propia": "Terminar sessão",
        "Cerrar": "Fechar",
        "Codex CLI detectado": "Codex CLI detetado",
        "Codex CLI no encontrado": "Codex CLI não encontrado",
        "Conectar con %@": "Ligar a %@",
        "Conectar": "Ligar",
        "Consumido": "Consumido",
        "Copiar enlace de autorización": "Copiar link de autorização",
        "Coste de hoy (total)": "Custo de hoje (total)",
        "Coste": "Custo",
        "Créditos": "Créditos",
        "Cuenta": "Conta",
        "Datos locales": "Dados locais",
        "Entrada": "Entrada",
        "Esperando autorización…": "A aguardar autorização…",
        "Esperando la autorización del navegador…": "A aguardar a autorização do navegador…",
        "Hoy": "Hoje",
        "Ilimitados": "Ilimitados",
        "Iniciar sesión con %@": "Iniciar sessão com %@",
        "Iniciar sesión con Claude…": "Iniciar sessão com Claude…",
        "Iniciar sesión con OpenAI…": "Iniciar sessão com OpenAI…",
        "Intercambiando el código por la sesión…": "A trocar o código pela sessão…",
        "JSON inesperado": "JSON inesperado",
        "La barra de menús muestra": "A barra de menus mostra",
        "La sesión se guarda en un ítem propio del llavero. La app no lee las credenciales de Claude Code, así que macOS no pide permisos de acceso.": "A sessão é guardada num item próprio das Porta-chaves. A app nunca lê as credenciais do Claude Code, pelo que o macOS não pedirá acesso.",
        "Leyendo datos de uso…": "A ler dados de utilização…",
        "Los tokens salen de las sesiones locales de Codex CLI (~/.codex/sessions). Los límites del plan se consultan en vivo a chatgpt.com con tu sesión de OpenAI.": "Os tokens vêm das sessões locais do Codex CLI (~/.codex/sessions). Os limites do plano são consultados em direto em chatgpt.com com a tua sessão OpenAI.",
        "Límite alcanzado: %@": "Limite atingido: %@",
        "Límite de gasto": "Limite de gastos",
        "Límite": "Limite",
        "Límites del plan": "Limites do plano",
        "Límites: %@": "Limites: %@",
        "Mensajes": "Mensagens",
        "Modelo": "Modelo",
        "Mostrar límites como": "Mostrar limites como",
        "No se han encontrado sesiones de Codex CLI en ~/.codex.": "Não foram encontradas sessões do Codex CLI em ~/.codex.",
        "Opus · semana": "Opus · semana",
        "Por modelo (últimos 30 días)": "Por modelo (últimos 30 dias)",
        "Reintentar": "Tentar novamente",
        "Restante": "Restante",
        "Restaurar orden por defecto": "Repor ordem predefinida",
        "Salida": "Saída",
        "Salir completamente": "Sair completamente",
        "Salir": "Sair",
        "Se abrirá el navegador para autorizar el acceso con tu cuenta de Claude (el mismo flujo que usa Claude Code). Al aceptar, la app recibirá la autorización automáticamente.": "O navegador vai abrir para autorizar o acesso com a tua conta Claude (o mesmo fluxo do Claude Code). Ao aceitar, a app recebe a autorização automaticamente.",
        "Se abrirá el navegador para autorizar el acceso con tu cuenta de OpenAI/ChatGPT (el mismo flujo que usa Codex CLI). Al aceptar, la app recibirá la autorización automáticamente.": "O navegador vai abrir para autorizar o acesso com a tua conta OpenAI/ChatGPT (o mesmo fluxo do Codex CLI). Ao aceitar, a app recebe a autorização automaticamente.",
        "Se reinicia el %@ a las %@": "Reinicia a %@ às %@",
        "Se reinicia en %@ (%@)": "Reinicia em %@ (%@)",
        "Secciones del menú": "Secções do menu",
        "Semana": "Semana",
        "Sesión (5 h)": "Sessão (5 h)",
        "Sesión iniciada correctamente": "Sessão iniciada com sucesso",
        "Sesión": "Sessão",
        "Sonnet · semana": "Sonnet · semana",
        "Uso extra (mes)": "Utilização extra (mês)",
        "Visualización": "Visualização",
        "Ya puedes cerrar esta pestaña y volver a AI Usage.": "Já podes fechar este separador e voltar ao AI Usage.",
        "auth.json de Codex CLI": "auth.json do Codex CLI",
        "caché": "cache",
        "créditos de tu usuario del workspace agotados": "créditos do teu utilizador do workspace esgotados",
        "créditos del propietario del workspace agotados": "créditos do proprietário do workspace esgotados",
        "código#estado": "código#estado",
        "de": "de",
        "días": "dias",
        "el puerto %@ está ocupado — ciérralo (p. ej. un «codex login» a medias) y reintenta": "a porta %@ está ocupada — fecha o que a está a usar (p. ex. um 'codex login' pendente) e tenta novamente",
        "entrada": "entrada",
        "libre": "livre",
        "límite de uso alcanzado": "limite de utilização atingido",
        "límite de uso de tu usuario alcanzado": "limite de utilização do teu utilizador atingido",
        "límite de uso del workspace alcanzado": "limite de utilização do workspace atingido",
        "límite": "limite",
        "mensajes": "mensagens",
        "propia de la app (caduca %@)": "própria da app (expira %@)",
        "propia de la app (renovación automática)": "própria da app (renovação automática)",
        "propia de la app": "própria da app",
        "respuesta no válida": "resposta inválida",
        "salida": "saída",
        "sesión caducada — vuelve a iniciar sesión": "sessão expirada — inicia sessão novamente",
        "sesión no autorizada — vuelve a iniciar sesión": "sessão não autorizada — inicia sessão novamente",
        "sin actividad reciente": "sem atividade recente",
        "sin datos de límites": "sem dados de limites",
        "sin sesión — conéctate con tu cuenta de Claude": "sem sessão — inicia sessão com a tua conta Claude",
        "sin sesión — conéctate con tu cuenta de OpenAI": "sem sessão — inicia sessão com a tua conta OpenAI",
        "sin sesión": "sem sessão",
        "termina a las %@ · quedan %@": "termina às %@ · faltam %@",
        "termina a las %@": "termina às %@",
        "tope de gasto alcanzado": "teto de gastos atingido",
        "usado": "usado",
        "¿No vuelve solo? Pega el código manualmente": "Não volta sozinho? Cola o código manualmente",
        "Últimos 14 días": "Últimos 14 dias",
        "Últimos 30 días": "Últimos 30 dias",
        "Últimos 7 días (total)": "Últimos 7 dias (total)",
        "Últimos 7 días": "Últimos 7 dias",
    ]

    private static let ja: [String: String] = [
        "%d turnos en 30 días": "過去30日間で%dターン",
        "Abrir AI Usage": "AI Usageを開く",
        "Abrir al iniciar sesión en el Mac": "ログイン時に開く",
        "Abrir navegador para autorizar": "ブラウザで認証する",
        "Abrir panel": "パネルを開く",
        "Actualizado a las %@": "%@ に更新",
        "Actualizar ahora": "今すぐ更新",
        "Ajustes": "設定",
        "Ajustes…": "設定…",
        "Apps · semana": "アプリ · 週",
        "Automático (Claude primero)": "自動（Claude優先）",
        "Autoriza en el navegador y pega abajo el código que se muestra.": "ブラウザで認証し、表示されたコードを下に貼り付けてください。",
        "Autorizado": "認証されました",
        "Bloque actual (5 h)": "現在のブロック（5時間）",
        "Caché": "キャッシュ",
        "Cancelar": "キャンセル",
        "Cerrar sesión propia": "ログアウト",
        "Cerrar": "閉じる",
        "Codex CLI detectado": "Codex CLIを検出",
        "Codex CLI no encontrado": "Codex CLIが見つかりません",
        "Conectar con %@": "%@ に接続",
        "Conectar": "接続",
        "Consumido": "使用済み",
        "Copiar enlace de autorización": "認証リンクをコピー",
        "Coste de hoy (total)": "今日のコスト（合計）",
        "Coste": "コスト",
        "Créditos": "クレジット",
        "Cuenta": "アカウント",
        "Datos locales": "ローカルデータ",
        "Entrada": "入力",
        "Esperando autorización…": "認証を待っています…",
        "Esperando la autorización del navegador…": "ブラウザでの認証を待っています…",
        "Hoy": "今日",
        "Ilimitados": "無制限",
        "Iniciar sesión con %@": "%@ でサインイン",
        "Iniciar sesión con Claude…": "Claudeでサインイン…",
        "Iniciar sesión con OpenAI…": "OpenAIでサインイン…",
        "Intercambiando el código por la sesión…": "コードをセッションと交換中…",
        "JSON inesperado": "予期しないJSON",
        "La barra de menús muestra": "メニューバーの表示",
        "La sesión se guarda en un ítem propio del llavero. La app no lee las credenciales de Claude Code, así que macOS no pide permisos de acceso.": "セッションはアプリ専用のキーチェーン項目に保存されます。Claude Codeの認証情報は読み取らないため、macOSがアクセス許可を求めることはありません。",
        "Leyendo datos de uso…": "使用データを読み込み中…",
        "Los tokens salen de las sesiones locales de Codex CLI (~/.codex/sessions). Los límites del plan se consultan en vivo a chatgpt.com con tu sesión de OpenAI.": "トークンはCodex CLIのローカルセッション（~/.codex/sessions）から取得します。プランの上限はOpenAIセッションを使ってchatgpt.comからリアルタイムに取得します。",
        "Límite alcanzado: %@": "上限に達しました：%@",
        "Límite de gasto": "支出上限",
        "Límite": "上限",
        "Límites del plan": "プランの上限",
        "Límites: %@": "上限：%@",
        "Mensajes": "メッセージ",
        "Modelo": "モデル",
        "Mostrar límites como": "上限の表示方法",
        "No se han encontrado sesiones de Codex CLI en ~/.codex.": "~/.codex にCodex CLIのセッションが見つかりません。",
        "Opus · semana": "Opus · 週",
        "Por modelo (últimos 30 días)": "モデル別（過去30日）",
        "Reintentar": "再試行",
        "Restante": "残り",
        "Restaurar orden por defecto": "デフォルトの順序に戻す",
        "Salida": "出力",
        "Salir completamente": "完全に終了",
        "Salir": "終了",
        "Se abrirá el navegador para autorizar el acceso con tu cuenta de Claude (el mismo flujo que usa Claude Code). Al aceptar, la app recibirá la autorización automáticamente.": "ブラウザが開き、Claudeアカウントでアクセスを認証します（Claude Codeと同じフロー）。承認すると、アプリは自動的に認証を受け取ります。",
        "Se abrirá el navegador para autorizar el acceso con tu cuenta de OpenAI/ChatGPT (el mismo flujo que usa Codex CLI). Al aceptar, la app recibirá la autorización automáticamente.": "ブラウザが開き、OpenAI/ChatGPTアカウントでアクセスを認証します（Codex CLIと同じフロー）。承認すると、アプリは自動的に認証を受け取ります。",
        "Se reinicia el %@ a las %@": "%@ %@ にリセット",
        "Se reinicia en %@ (%@)": "%@後にリセット（%@）",
        "Secciones del menú": "メニューのセクション",
        "Semana": "週",
        "Sesión (5 h)": "セッション（5時間）",
        "Sesión iniciada correctamente": "サインインしました",
        "Sesión": "セッション",
        "Sonnet · semana": "Sonnet · 週",
        "Uso extra (mes)": "追加使用（月）",
        "Visualización": "表示",
        "Ya puedes cerrar esta pestaña y volver a AI Usage.": "このタブを閉じてAI Usageに戻れます。",
        "auth.json de Codex CLI": "Codex CLIのauth.json",
        "caché": "キャッシュ",
        "créditos de tu usuario del workspace agotados": "ワークスペースのあなたのクレジットが枯渇",
        "créditos del propietario del workspace agotados": "ワークスペース所有者のクレジットが枯渇",
        "código#estado": "コード#ステート",
        "de": "/",
        "días": "日",
        "el puerto %@ está ocupado — ciérralo (p. ej. un «codex login» a medias) y reintenta": "ポート%@が使用中です — 使用中のプロセス（例：進行中の codex login）を終了して再試行してください",
        "entrada": "入力",
        "libre": "残り",
        "límite de uso alcanzado": "使用上限に達しました",
        "límite de uso de tu usuario alcanzado": "あなたの使用上限に達しました",
        "límite de uso del workspace alcanzado": "ワークスペースの使用上限に達しました",
        "límite": "上限",
        "mensajes": "メッセージ",
        "propia de la app (caduca %@)": "アプリ独自（%@ に期限切れ）",
        "propia de la app (renovación automática)": "アプリ独自（自動更新）",
        "propia de la app": "アプリ独自",
        "respuesta no válida": "無効な応答",
        "salida": "出力",
        "sesión caducada — vuelve a iniciar sesión": "セッションの期限切れ — 再度サインインしてください",
        "sesión no autorizada — vuelve a iniciar sesión": "セッションが未認証 — 再度サインインしてください",
        "sin actividad reciente": "最近のアクティビティなし",
        "sin datos de límites": "上限データなし",
        "sin sesión — conéctate con tu cuenta de Claude": "セッションなし — Claudeアカウントでサインインしてください",
        "sin sesión — conéctate con tu cuenta de OpenAI": "セッションなし — OpenAIアカウントでサインインしてください",
        "sin sesión": "セッションなし",
        "termina a las %@ · quedan %@": "%@ に終了 · 残り %@",
        "termina a las %@": "%@ に終了",
        "tope de gasto alcanzado": "支出上限に達しました",
        "usado": "使用",
        "¿No vuelve solo? Pega el código manualmente": "自動で戻らない場合はコードを手動で貼り付け",
        "Últimos 14 días": "過去14日",
        "Últimos 30 días": "過去30日",
        "Últimos 7 días (total)": "過去7日（合計）",
        "Últimos 7 días": "過去7日",
    ]

    private static let zh: [String: String] = [
        "%d turnos en 30 días": "30天内%d个回合",
        "Abrir AI Usage": "打开 AI Usage",
        "Abrir al iniciar sesión en el Mac": "登录时打开",
        "Abrir navegador para autorizar": "打开浏览器进行授权",
        "Abrir panel": "打开面板",
        "Actualizado a las %@": "更新于 %@",
        "Actualizar ahora": "立即刷新",
        "Ajustes": "设置",
        "Ajustes…": "设置…",
        "Apps · semana": "应用 · 周",
        "Automático (Claude primero)": "自动（Claude 优先）",
        "Autoriza en el navegador y pega abajo el código que se muestra.": "在浏览器中授权，然后将显示的代码粘贴到下方。",
        "Autorizado": "已授权",
        "Bloque actual (5 h)": "当前时段（5 小时）",
        "Caché": "缓存",
        "Cancelar": "取消",
        "Cerrar sesión propia": "退出登录",
        "Cerrar": "关闭",
        "Codex CLI detectado": "已检测到 Codex CLI",
        "Codex CLI no encontrado": "未找到 Codex CLI",
        "Conectar con %@": "连接 %@",
        "Conectar": "连接",
        "Consumido": "已用",
        "Copiar enlace de autorización": "复制授权链接",
        "Coste de hoy (total)": "今日成本（总计）",
        "Coste": "成本",
        "Créditos": "额度",
        "Cuenta": "账户",
        "Datos locales": "本地数据",
        "Entrada": "输入",
        "Esperando autorización…": "等待授权…",
        "Esperando la autorización del navegador…": "等待浏览器授权…",
        "Hoy": "今天",
        "Ilimitados": "无限",
        "Iniciar sesión con %@": "使用 %@ 登录",
        "Iniciar sesión con Claude…": "使用 Claude 登录…",
        "Iniciar sesión con OpenAI…": "使用 OpenAI 登录…",
        "Intercambiando el código por la sesión…": "正在用代码换取会话…",
        "JSON inesperado": "意外的 JSON",
        "La barra de menús muestra": "菜单栏显示",
        "La sesión se guarda en un ítem propio del llavero. La app no lee las credenciales de Claude Code, así que macOS no pide permisos de acceso.": "会话保存在应用自己的钥匙串项中。应用不会读取 Claude Code 的凭据，因此 macOS 不会请求访问权限。",
        "Leyendo datos de uso…": "正在读取使用数据…",
        "Los tokens salen de las sesiones locales de Codex CLI (~/.codex/sessions). Los límites del plan se consultan en vivo a chatgpt.com con tu sesión de OpenAI.": "Token 数据来自 Codex CLI 的本地会话（~/.codex/sessions）。套餐限额通过你的 OpenAI 会话从 chatgpt.com 实时获取。",
        "Límite alcanzado: %@": "已达上限：%@",
        "Límite de gasto": "支出限额",
        "Límite": "限额",
        "Límites del plan": "套餐限额",
        "Límites: %@": "限额：%@",
        "Mensajes": "消息",
        "Modelo": "模型",
        "Mostrar límites como": "限额显示为",
        "No se han encontrado sesiones de Codex CLI en ~/.codex.": "在 ~/.codex 中未找到 Codex CLI 会话。",
        "Opus · semana": "Opus · 周",
        "Por modelo (últimos 30 días)": "按模型（最近 30 天）",
        "Reintentar": "重试",
        "Restante": "剩余",
        "Restaurar orden por defecto": "恢复默认顺序",
        "Salida": "输出",
        "Salir completamente": "完全退出",
        "Salir": "退出",
        "Se abrirá el navegador para autorizar el acceso con tu cuenta de Claude (el mismo flujo que usa Claude Code). Al aceptar, la app recibirá la autorización automáticamente.": "浏览器将打开以使用你的 Claude 账户授权（与 Claude Code 相同的流程）。同意后，应用会自动收到授权。",
        "Se abrirá el navegador para autorizar el acceso con tu cuenta de OpenAI/ChatGPT (el mismo flujo que usa Codex CLI). Al aceptar, la app recibirá la autorización automáticamente.": "浏览器将打开以使用你的 OpenAI/ChatGPT 账户授权（与 Codex CLI 相同的流程）。同意后，应用会自动收到授权。",
        "Se reinicia el %@ a las %@": "将于 %@ %@ 重置",
        "Se reinicia en %@ (%@)": "%@后重置（%@）",
        "Secciones del menú": "菜单栏目",
        "Semana": "周",
        "Sesión (5 h)": "会话（5 小时）",
        "Sesión iniciada correctamente": "登录成功",
        "Sesión": "会话",
        "Sonnet · semana": "Sonnet · 周",
        "Uso extra (mes)": "额外用量（月）",
        "Visualización": "显示",
        "Ya puedes cerrar esta pestaña y volver a AI Usage.": "现在可以关闭此标签页并返回 AI Usage。",
        "auth.json de Codex CLI": "Codex CLI 的 auth.json",
        "caché": "缓存",
        "créditos de tu usuario del workspace agotados": "你的工作区额度已用尽",
        "créditos del propietario del workspace agotados": "工作区所有者的额度已用尽",
        "código#estado": "代码#状态",
        "de": "/",
        "días": "天",
        "el puerto %@ está ocupado — ciérralo (p. ej. un «codex login» a medias) y reintenta": "端口 %@ 被占用 — 请关闭占用它的程序（例如未完成的 codex login）后重试",
        "entrada": "输入",
        "libre": "剩余",
        "límite de uso alcanzado": "已达使用上限",
        "límite de uso de tu usuario alcanzado": "已达你的使用上限",
        "límite de uso del workspace alcanzado": "已达工作区使用上限",
        "límite": "限额",
        "mensajes": "条消息",
        "propia de la app (caduca %@)": "应用自有（%@ 过期）",
        "propia de la app (renovación automática)": "应用自有（自动续期）",
        "propia de la app": "应用自有",
        "respuesta no válida": "无效响应",
        "salida": "输出",
        "sesión caducada — vuelve a iniciar sesión": "会话已过期 — 请重新登录",
        "sesión no autorizada — vuelve a iniciar sesión": "会话未授权 — 请重新登录",
        "sin actividad reciente": "近期无活动",
        "sin datos de límites": "无限额数据",
        "sin sesión — conéctate con tu cuenta de Claude": "无会话 — 请使用 Claude 账户登录",
        "sin sesión — conéctate con tu cuenta de OpenAI": "无会话 — 请使用 OpenAI 账户登录",
        "sin sesión": "无会话",
        "termina a las %@ · quedan %@": "%@ 结束 · 剩余 %@",
        "termina a las %@": "%@ 结束",
        "tope de gasto alcanzado": "已达支出上限",
        "usado": "已用",
        "¿No vuelve solo? Pega el código manualmente": "没有自动返回？手动粘贴代码",
        "Últimos 14 días": "最近 14 天",
        "Últimos 30 días": "最近 30 天",
        "Últimos 7 días (total)": "最近 7 天（总计）",
        "Últimos 7 días": "最近 7 天",
    ]

    private static let ko: [String: String] = [
        "%d turnos en 30 días": "30일간 %d턴",
        "Abrir AI Usage": "AI Usage 열기",
        "Abrir al iniciar sesión en el Mac": "로그인 시 열기",
        "Abrir navegador para autorizar": "브라우저에서 인증하기",
        "Abrir panel": "패널 열기",
        "Actualizado a las %@": "%@에 업데이트됨",
        "Actualizar ahora": "지금 새로고침",
        "Ajustes": "설정",
        "Ajustes…": "설정…",
        "Apps · semana": "앱 · 주간",
        "Automático (Claude primero)": "자동 (Claude 우선)",
        "Autoriza en el navegador y pega abajo el código que se muestra.": "브라우저에서 인증한 후 표시된 코드를 아래에 붙여넣으세요.",
        "Autorizado": "인증 완료",
        "Bloque actual (5 h)": "현재 블록 (5시간)",
        "Caché": "캐시",
        "Cancelar": "취소",
        "Cerrar sesión propia": "로그아웃",
        "Cerrar": "닫기",
        "Codex CLI detectado": "Codex CLI 감지됨",
        "Codex CLI no encontrado": "Codex CLI를 찾을 수 없음",
        "Conectar con %@": "%@ 연결",
        "Conectar": "연결",
        "Consumido": "사용량",
        "Copiar enlace de autorización": "인증 링크 복사",
        "Coste de hoy (total)": "오늘 비용 (합계)",
        "Coste": "비용",
        "Créditos": "크레딧",
        "Cuenta": "계정",
        "Datos locales": "로컬 데이터",
        "Entrada": "입력",
        "Esperando autorización…": "인증 대기 중…",
        "Esperando la autorización del navegador…": "브라우저 인증 대기 중…",
        "Hoy": "오늘",
        "Ilimitados": "무제한",
        "Iniciar sesión con %@": "%@ 로그인",
        "Iniciar sesión con Claude…": "Claude 로그인…",
        "Iniciar sesión con OpenAI…": "OpenAI 로그인…",
        "Intercambiando el código por la sesión…": "코드를 세션으로 교환 중…",
        "JSON inesperado": "예기치 않은 JSON",
        "La barra de menús muestra": "메뉴 막대 표시",
        "La sesión se guarda en un ítem propio del llavero. La app no lee las credenciales de Claude Code, así que macOS no pide permisos de acceso.": "세션은 앱 전용 키체인 항목에 저장됩니다. 앱은 Claude Code의 자격 증명을 읽지 않으므로 macOS가 접근 권한을 요청하지 않습니다.",
        "Leyendo datos de uso…": "사용 데이터 읽는 중…",
        "Los tokens salen de las sesiones locales de Codex CLI (~/.codex/sessions). Los límites del plan se consultan en vivo a chatgpt.com con tu sesión de OpenAI.": "토큰은 Codex CLI 로컬 세션(~/.codex/sessions)에서 가져옵니다. 플랜 한도는 OpenAI 세션으로 chatgpt.com에서 실시간 조회합니다.",
        "Límite alcanzado: %@": "한도 도달: %@",
        "Límite de gasto": "지출 한도",
        "Límite": "한도",
        "Límites del plan": "플랜 한도",
        "Límites: %@": "한도: %@",
        "Mensajes": "메시지",
        "Modelo": "모델",
        "Mostrar límites como": "한도 표시 방식",
        "No se han encontrado sesiones de Codex CLI en ~/.codex.": "~/.codex에서 Codex CLI 세션을 찾을 수 없습니다.",
        "Opus · semana": "Opus · 주간",
        "Por modelo (últimos 30 días)": "모델별 (최근 30일)",
        "Reintentar": "다시 시도",
        "Restante": "남은 양",
        "Restaurar orden por defecto": "기본 순서 복원",
        "Salida": "출력",
        "Salir completamente": "완전히 종료",
        "Salir": "종료",
        "Se abrirá el navegador para autorizar el acceso con tu cuenta de Claude (el mismo flujo que usa Claude Code). Al aceptar, la app recibirá la autorización automáticamente.": "브라우저가 열리고 Claude 계정으로 접근을 인증합니다(Claude Code와 동일한 방식). 승인하면 앱이 자동으로 인증을 받습니다.",
        "Se abrirá el navegador para autorizar el acceso con tu cuenta de OpenAI/ChatGPT (el mismo flujo que usa Codex CLI). Al aceptar, la app recibirá la autorización automáticamente.": "브라우저가 열리고 OpenAI/ChatGPT 계정으로 접근을 인증합니다(Codex CLI와 동일한 방식). 승인하면 앱이 자동으로 인증을 받습니다.",
        "Se reinicia el %@ a las %@": "%@ %@에 초기화",
        "Se reinicia en %@ (%@)": "%@ 후 초기화 (%@)",
        "Secciones del menú": "메뉴 섹션",
        "Semana": "주간",
        "Sesión (5 h)": "세션 (5시간)",
        "Sesión iniciada correctamente": "로그인 성공",
        "Sesión": "세션",
        "Sonnet · semana": "Sonnet · 주간",
        "Uso extra (mes)": "추가 사용량 (월)",
        "Visualización": "표시",
        "Ya puedes cerrar esta pestaña y volver a AI Usage.": "이 탭을 닫고 AI Usage로 돌아가세요.",
        "auth.json de Codex CLI": "Codex CLI의 auth.json",
        "caché": "캐시",
        "créditos de tu usuario del workspace agotados": "워크스페이스 내 크레딧 소진",
        "créditos del propietario del workspace agotados": "워크스페이스 소유자 크레딧 소진",
        "código#estado": "코드#상태",
        "de": "/",
        "días": "일",
        "el puerto %@ está ocupado — ciérralo (p. ej. un «codex login» a medias) y reintenta": "포트 %@이(가) 사용 중입니다 — 사용 중인 프로세스(예: 진행 중인 codex login)를 종료하고 다시 시도하세요",
        "entrada": "입력",
        "libre": "남음",
        "límite de uso alcanzado": "사용 한도 도달",
        "límite de uso de tu usuario alcanzado": "내 사용 한도 도달",
        "límite de uso del workspace alcanzado": "워크스페이스 사용 한도 도달",
        "límite": "한도",
        "mensajes": "메시지",
        "propia de la app (caduca %@)": "앱 자체 세션 (%@ 만료)",
        "propia de la app (renovación automática)": "앱 자체 세션 (자동 갱신)",
        "propia de la app": "앱 자체 세션",
        "respuesta no válida": "잘못된 응답",
        "salida": "출력",
        "sesión caducada — vuelve a iniciar sesión": "세션 만료 — 다시 로그인하세요",
        "sesión no autorizada — vuelve a iniciar sesión": "세션 인증 안 됨 — 다시 로그인하세요",
        "sin actividad reciente": "최근 활동 없음",
        "sin datos de límites": "한도 데이터 없음",
        "sin sesión — conéctate con tu cuenta de Claude": "세션 없음 — Claude 계정으로 로그인하세요",
        "sin sesión — conéctate con tu cuenta de OpenAI": "세션 없음 — OpenAI 계정으로 로그인하세요",
        "sin sesión": "세션 없음",
        "termina a las %@ · quedan %@": "%@ 종료 · %@ 남음",
        "termina a las %@": "%@ 종료",
        "tope de gasto alcanzado": "지출 상한 도달",
        "usado": "사용",
        "¿No vuelve solo? Pega el código manualmente": "자동으로 돌아오지 않나요? 코드를 직접 붙여넣기",
        "Últimos 14 días": "최근 14일",
        "Últimos 30 días": "최근 30일",
        "Últimos 7 días (total)": "최근 7일 (합계)",
        "Últimos 7 días": "최근 7일",
    ]

    private static let ru: [String: String] = [
        "%d turnos en 30 días": "%d ходов за 30 дней",
        "Abrir AI Usage": "Открыть AI Usage",
        "Abrir al iniciar sesión en el Mac": "Открывать при входе в систему",
        "Abrir navegador para autorizar": "Открыть браузер для авторизации",
        "Abrir panel": "Открыть панель",
        "Actualizado a las %@": "Обновлено в %@",
        "Actualizar ahora": "Обновить сейчас",
        "Ajustes": "Настройки",
        "Ajustes…": "Настройки…",
        "Apps · semana": "Приложения · неделя",
        "Automático (Claude primero)": "Автоматически (сначала Claude)",
        "Autoriza en el navegador y pega abajo el código que se muestra.": "Авторизуйтесь в браузере и вставьте показанный код ниже.",
        "Autorizado": "Авторизовано",
        "Bloque actual (5 h)": "Текущий блок (5 ч)",
        "Caché": "Кэш",
        "Cancelar": "Отмена",
        "Cerrar sesión propia": "Выйти",
        "Cerrar": "Закрыть",
        "Codex CLI detectado": "Codex CLI обнаружен",
        "Codex CLI no encontrado": "Codex CLI не найден",
        "Conectar con %@": "Подключить %@",
        "Conectar": "Подключить",
        "Consumido": "Использовано",
        "Copiar enlace de autorización": "Скопировать ссылку авторизации",
        "Coste de hoy (total)": "Стоимость за сегодня (всего)",
        "Coste": "Стоимость",
        "Créditos": "Кредиты",
        "Cuenta": "Аккаунт",
        "Datos locales": "Локальные данные",
        "Entrada": "Ввод",
        "Esperando autorización…": "Ожидание авторизации…",
        "Esperando la autorización del navegador…": "Ожидание авторизации в браузере…",
        "Hoy": "Сегодня",
        "Ilimitados": "Безлимит",
        "Iniciar sesión con %@": "Войти через %@",
        "Iniciar sesión con Claude…": "Войти через Claude…",
        "Iniciar sesión con OpenAI…": "Войти через OpenAI…",
        "Intercambiando el código por la sesión…": "Обмен кода на сессию…",
        "JSON inesperado": "Неожиданный JSON",
        "La barra de menús muestra": "В строке меню показывать",
        "La sesión se guarda en un ítem propio del llavero. La app no lee las credenciales de Claude Code, así que macOS no pide permisos de acceso.": "Сессия хранится в собственном элементе связки ключей приложения. Приложение не читает учётные данные Claude Code, поэтому macOS не будет запрашивать доступ.",
        "Leyendo datos de uso…": "Чтение данных об использовании…",
        "Los tokens salen de las sesiones locales de Codex CLI (~/.codex/sessions). Los límites del plan se consultan en vivo a chatgpt.com con tu sesión de OpenAI.": "Токены берутся из локальных сессий Codex CLI (~/.codex/sessions). Лимиты тарифа запрашиваются в реальном времени с chatgpt.com через вашу сессию OpenAI.",
        "Límite alcanzado: %@": "Лимит достигнут: %@",
        "Límite de gasto": "Лимит расходов",
        "Límite": "Лимит",
        "Límites del plan": "Лимиты тарифа",
        "Límites: %@": "Лимиты: %@",
        "Mensajes": "Сообщения",
        "Modelo": "Модель",
        "Mostrar límites como": "Показывать лимиты как",
        "No se han encontrado sesiones de Codex CLI en ~/.codex.": "Сессии Codex CLI в ~/.codex не найдены.",
        "Opus · semana": "Opus · неделя",
        "Por modelo (últimos 30 días)": "По моделям (последние 30 дней)",
        "Reintentar": "Повторить",
        "Restante": "Осталось",
        "Restaurar orden por defecto": "Восстановить порядок по умолчанию",
        "Salida": "Вывод",
        "Salir completamente": "Полностью выйти",
        "Salir": "Выход",
        "Se abrirá el navegador para autorizar el acceso con tu cuenta de Claude (el mismo flujo que usa Claude Code). Al aceptar, la app recibirá la autorización automáticamente.": "Откроется браузер для авторизации доступа с вашим аккаунтом Claude (тот же процесс, что и в Claude Code). После подтверждения приложение получит авторизацию автоматически.",
        "Se abrirá el navegador para autorizar el acceso con tu cuenta de OpenAI/ChatGPT (el mismo flujo que usa Codex CLI). Al aceptar, la app recibirá la autorización automáticamente.": "Откроется браузер для авторизации доступа с вашим аккаунтом OpenAI/ChatGPT (тот же процесс, что и в Codex CLI). После подтверждения приложение получит авторизацию автоматически.",
        "Se reinicia el %@ a las %@": "Сброс %@ в %@",
        "Se reinicia en %@ (%@)": "Сброс через %@ (%@)",
        "Secciones del menú": "Разделы меню",
        "Semana": "Неделя",
        "Sesión (5 h)": "Сессия (5 ч)",
        "Sesión iniciada correctamente": "Вход выполнен",
        "Sesión": "Сессия",
        "Sonnet · semana": "Sonnet · неделя",
        "Uso extra (mes)": "Доп. использование (месяц)",
        "Visualización": "Отображение",
        "Ya puedes cerrar esta pestaña y volver a AI Usage.": "Можно закрыть эту вкладку и вернуться в AI Usage.",
        "auth.json de Codex CLI": "auth.json из Codex CLI",
        "caché": "кэш",
        "créditos de tu usuario del workspace agotados": "кредиты вашего пользователя в workspace исчерпаны",
        "créditos del propietario del workspace agotados": "кредиты владельца workspace исчерпаны",
        "código#estado": "код#состояние",
        "de": "из",
        "días": "дней",
        "el puerto %@ está ocupado — ciérralo (p. ej. un «codex login» a medias) y reintenta": "порт %@ занят — закройте использующий его процесс (например, незавершённый codex login) и повторите",
        "entrada": "ввод",
        "libre": "свободно",
        "límite de uso alcanzado": "достигнут лимит использования",
        "límite de uso de tu usuario alcanzado": "достигнут лимит вашего пользователя",
        "límite de uso del workspace alcanzado": "достигнут лимит workspace",
        "límite": "лимит",
        "mensajes": "сообщений",
        "propia de la app (caduca %@)": "собственная (истекает %@)",
        "propia de la app (renovación automática)": "собственная (автообновление)",
        "propia de la app": "собственная",
        "respuesta no válida": "недопустимый ответ",
        "salida": "вывод",
        "sesión caducada — vuelve a iniciar sesión": "сессия истекла — войдите снова",
        "sesión no autorizada — vuelve a iniciar sesión": "сессия не авторизована — войдите снова",
        "sin actividad reciente": "нет недавней активности",
        "sin datos de límites": "нет данных о лимитах",
        "sin sesión — conéctate con tu cuenta de Claude": "нет сессии — войдите с аккаунтом Claude",
        "sin sesión — conéctate con tu cuenta de OpenAI": "нет сессии — войдите с аккаунтом OpenAI",
        "sin sesión": "нет сессии",
        "termina a las %@ · quedan %@": "заканчивается в %@ · осталось %@",
        "termina a las %@": "заканчивается в %@",
        "tope de gasto alcanzado": "достигнут потолок расходов",
        "usado": "занято",
        "¿No vuelve solo? Pega el código manualmente": "Не вернулось само? Вставьте код вручную",
        "Últimos 14 días": "Последние 14 дней",
        "Últimos 30 días": "Последние 30 дней",
        "Últimos 7 días (total)": "Последние 7 дней (всего)",
        "Últimos 7 días": "Последние 7 дней",
    ]
}
