//
//  Localization.swift
//  AI Usage
//
//  Copyright © 2026 Aitor Sola. All rights reserved.
//

import Foundation

enum AppLanguage: String {
    case es, en, fr, de, it, pt, ja, zh, ko, ru

    static let current: AppLanguage = {
        for raw in Locale.preferredLanguages {
            let code = raw.lowercased()
            if code.hasPrefix("es") { return .es }
            if code.hasPrefix("en") { return .en }
            if code.hasPrefix("fr") { return .fr }
            if code.hasPrefix("de") { return .de }
            if code.hasPrefix("it") { return .it }
            if code.hasPrefix("pt") { return .pt }
            if code.hasPrefix("ja") { return .ja }
            if code.hasPrefix("zh") { return .zh }
            if code.hasPrefix("ko") { return .ko }
            if code.hasPrefix("ru") { return .ru }
        }
        return .en
    }()
}

enum L {
    static func t(_ key: String) -> String {
        let lang = AppLanguage.current
        return Translations.tables[lang]?[key]
            ?? Translations.tables[.en]?[key]
            ?? key
    }
}

enum Translations {
    static let tables: [AppLanguage: [String: String]] = [
        .es: es, .en: en, .fr: fr, .de: de, .it: it, .pt: pt, .ja: ja, .zh: zh, .ko: ko, .ru: ru,
    ]

    private static let es: [String: String] = [
        "unknown_error": "Error desconocido",
        "plan_badge": "Plan %@",
        "balance": "Saldo",
        "add_deepseek_key_in_settings": "Añade tu API key de DeepSeek en Ajustes.",
        "balance_depleted": "Saldo agotado",
        "deepseek_caption": "Créditos prepago de la API de DeepSeek. La clave se guarda en el llavero y solo consulta tu saldo.",
        "invalid_api_key": "API key no válida",
        "no_opencode_data": "Sin datos de OpenCode",
        "open_settings": "Abrir Ajustes",
        "opencode_caption": "Tokens y coste leídos de la base de datos local de OpenCode. OpenCode no tiene plan, así que no hay porcentajes.",
        "paste_api_key": "Pega tu API key…",
        "save": "Guardar",
        "turns_in_30_days": "%d turnos en 30 días",
        "account": "Cuenta",
        "active": "Activa",
        "apps_week": "Apps · semana",
        "authorize_in_the_browser_and_paste": "Autoriza en el navegador y pega abajo el código que se muestra.",
        "authorized": "Autorizado",
        "automatic_claude_first": "Automático (Claude primero)",
        "by_model_last_30_days": "Por modelo (últimos 30 días)",
        "cache": "Caché",
        "cache_2": "caché",
        "cancel": "Cancelar",
        "close": "Cerrar",
        "code_state": "código#estado",
        "codex_cli_detected": "Codex CLI detectado",
        "codex_cli_not_found": "Codex CLI no encontrado",
        "connect": "Conectar",
        "connect_to": "Conectar con %@",
        "copy_authorization_link": "Copiar enlace de autorización",
        "cost": "Coste",
        "credits": "Créditos",
        "current_block_5_h": "Bloque actual (5 h)",
        "days": "días",
        "didnt_come_back_paste_the_code": "¿No vuelve solo? Pega el código manualmente",
        "display": "Visualización",
        "ends_at": "termina a las %@",
        "ends_at_left": "termina a las %@ · quedan %@",
        "exchanging_the_code_for_a_session": "Intercambiando el código por la sesión…",
        "extra_usage_month": "Uso extra (mes)",
        "input": "Entrada",
        "input_2": "entrada",
        "invalid_response": "respuesta no válida",
        "last_14_days": "Últimos 14 días",
        "last_30_days": "Últimos 30 días",
        "last_7_days": "Últimos 7 días",
        "last_7_days_total": "Últimos 7 días (total)",
        "left": "libre",
        "limit": "Límite",
        "limit_2": "límite",
        "limit_reached": "Límite alcanzado: %@",
        "limits": "Límites: %@",
        "local_data": "Datos locales",
        "menu_bar_shows": "La barra de menús muestra",
        "menu_sections": "Secciones del menú",
        "messages": "Mensajes",
        "messages_2": "mensajes",
        "model": "Modelo",
        "no_codex_cli_sessions_found_in": "No se han encontrado sesiones de Codex CLI en ~/.codex.",
        "no_limit_data": "sin datos de límites",
        "no_recent_activity": "sin actividad reciente",
        "no_session": "sin sesión",
        "no_session_sign_in_with_your": "sin sesión — conéctate con tu cuenta de Claude",
        "no_session_sign_in_with_your_2": "sin sesión — conéctate con tu cuenta de OpenAI",
        "not_signed_in": "Sin iniciar",
        "of": "de",
        "open_ai_usage": "Abrir AI Usage",
        "open_app": "Abrir app",
        "open_at_login": "Abrir al iniciar sesión en el Mac",
        "open_browser_to_authorize": "Abrir navegador para autorizar",
        "opus_week": "Opus · semana",
        "output": "Salida",
        "output_2": "salida",
        "plan_limits": "Límites del plan",
        "port_is_busy_close_whatever_is": "el puerto %@ está ocupado — ciérralo (p. ej. un «codex login» a medias) y reintenta",
        "quit": "Salir",
        "reading_usage_data": "Leyendo datos de uso…",
        "refresh_now": "Actualizar ahora",
        "remaining": "Restante",
        "resets_in": "Se reinicia en %@ (%@)",
        "resets_on_at": "Se reinicia el %@ a las %@",
        "restore_default_order": "Restaurar orden por defecto",
        "retry": "Reintentar",
        "session": "Sesión",
        "session_5_h": "Sesión (5 h)",
        "session_expired_sign_in_again": "sesión caducada — vuelve a iniciar sesión",
        "settings": "Ajustes",
        "settings_2": "Ajustes…",
        "show_limits_as": "Mostrar límites como",
        "sign_in_with": "Iniciar sesión con %@",
        "connect_with": "Conectar con %@",
        "sign_in_with_claude": "Iniciar sesión con Claude…",
        "sign_in_with_openai": "Iniciar sesión con OpenAI…",
        "sign_out": "Cerrar sesión",
        "signed_in_successfully": "Sesión iniciada correctamente",
        "sonnet_week": "Sonnet · semana",
        "spending_cap_reached": "tope de gasto alcanzado",
        "spending_limit": "Límite de gasto",
        "the_session_is_stored_in_the": "La sesión se guarda en un ítem propio del llavero. La app no lee las credenciales de Claude Code, así que macOS no pide permisos de acceso.",
        "today": "Hoy",
        "todays_cost_total": "Coste de hoy (total)",
        "token_counts_come_from_local_codex": "Los tokens salen de las sesiones locales de Codex CLI (~/.codex/sessions). Los límites del plan se consultan en vivo a chatgpt.com con tu sesión de OpenAI.",
        "unauthorized_sign_in_again": "sesión no autorizada — vuelve a iniciar sesión",
        "unexpected_json": "JSON inesperado",
        "unlimited": "Ilimitados",
        "updated_at": "Actualizado a las %@",
        "usage_limit_reached": "límite de uso alcanzado",
        "used": "Consumido",
        "used_2": "usado",
        "waiting_for_authorization": "Esperando autorización…",
        "waiting_for_browser_authorization": "Esperando la autorización del navegador…",
        "week": "Semana",
        "workspace_owner_credits_depleted": "créditos del propietario del workspace agotados",
        "workspace_usage_limit_reached": "límite de uso del workspace alcanzado",
        "you_can_close_this_tab_and": "Ya puedes cerrar esta pestaña y volver a AI Usage.",
        "your_browser_will_open_to_authorize": "Se abrirá el navegador para autorizar el acceso con tu cuenta de Claude (el mismo flujo que usa Claude Code). Al aceptar, la app recibirá la autorización automáticamente.",
        "your_browser_will_open_to_authorize_2": "Se abrirá el navegador para autorizar el acceso con tu cuenta de OpenAI/ChatGPT (el mismo flujo que usa Codex CLI). Al aceptar, la app recibirá la autorización automáticamente.",
        "your_usage_limit_was_reached": "límite de uso de tu usuario alcanzado",
        "your_workspace_credits_are_depleted": "créditos de tu usuario del workspace agotados",
    ]

    private static let en: [String: String] = [
        "unknown_error": "Unknown error",
        "plan_badge": "%@ plan",
        "balance": "Balance",
        "add_deepseek_key_in_settings": "Add your DeepSeek API key in Settings.",
        "balance_depleted": "Balance depleted",
        "deepseek_caption": "Prepaid credits from the DeepSeek API. The key is stored in the keychain and only reads your balance.",
        "invalid_api_key": "Invalid API key",
        "no_opencode_data": "No OpenCode data",
        "open_settings": "Open Settings",
        "opencode_caption": "Tokens and cost read from OpenCode's local database. OpenCode has no plan, so there are no percentages.",
        "paste_api_key": "Paste your API key…",
        "save": "Save",
        "turns_in_30_days": "%d turns in 30 days",
        "account": "Account",
        "active": "Active",
        "apps_week": "Apps · week",
        "authorize_in_the_browser_and_paste": "Authorize in the browser and paste the code shown below.",
        "authorized": "Authorized",
        "automatic_claude_first": "Automatic (Claude first)",
        "by_model_last_30_days": "By model (last 30 days)",
        "cache": "Cache",
        "cache_2": "cache",
        "cancel": "Cancel",
        "close": "Close",
        "code_state": "code#state",
        "codex_cli_detected": "Codex CLI detected",
        "codex_cli_not_found": "Codex CLI not found",
        "connect": "Connect",
        "connect_to": "Connect to %@",
        "copy_authorization_link": "Copy authorization link",
        "cost": "Cost",
        "credits": "Credits",
        "current_block_5_h": "Current block (5 h)",
        "days": "days",
        "didnt_come_back_paste_the_code": "Didn't come back? Paste the code manually",
        "display": "Display",
        "ends_at": "ends at %@",
        "ends_at_left": "ends at %@ · %@ left",
        "exchanging_the_code_for_a_session": "Exchanging the code for a session…",
        "extra_usage_month": "Extra usage (month)",
        "input": "Input",
        "input_2": "input",
        "invalid_response": "invalid response",
        "last_14_days": "Last 14 days",
        "last_30_days": "Last 30 days",
        "last_7_days": "Last 7 days",
        "last_7_days_total": "Last 7 days (total)",
        "left": "left",
        "limit": "Limit",
        "limit_2": "limit",
        "limit_reached": "Limit reached: %@",
        "limits": "Limits: %@",
        "local_data": "Local data",
        "menu_bar_shows": "Menu bar shows",
        "menu_sections": "Menu sections",
        "messages": "Messages",
        "messages_2": "messages",
        "model": "Model",
        "no_codex_cli_sessions_found_in": "No Codex CLI sessions found in ~/.codex.",
        "no_limit_data": "no limit data",
        "no_recent_activity": "no recent activity",
        "no_session": "no session",
        "no_session_sign_in_with_your": "no session — sign in with your Claude account",
        "no_session_sign_in_with_your_2": "no session — sign in with your OpenAI account",
        "not_signed_in": "Not signed in",
        "of": "of",
        "open_ai_usage": "Open AI Usage",
        "open_app": "Open app",
        "open_at_login": "Open at login",
        "open_browser_to_authorize": "Open browser to authorize",
        "opus_week": "Opus · week",
        "output": "Output",
        "output_2": "output",
        "plan_limits": "Plan limits",
        "port_is_busy_close_whatever_is": "port %@ is busy — close whatever is using it (e.g. a pending codex login) and retry",
        "quit": "Quit",
        "reading_usage_data": "Reading usage data…",
        "refresh_now": "Refresh now",
        "remaining": "Remaining",
        "resets_in": "Resets in %@ (%@)",
        "resets_on_at": "Resets on %@ at %@",
        "restore_default_order": "Restore default order",
        "retry": "Retry",
        "session": "Session",
        "session_5_h": "Session (5 h)",
        "session_expired_sign_in_again": "session expired — sign in again",
        "settings": "Settings",
        "settings_2": "Settings…",
        "show_limits_as": "Show limits as",
        "sign_in_with": "Sign in with %@",
        "connect_with": "Connect to %@",
        "sign_in_with_claude": "Sign in with Claude…",
        "sign_in_with_openai": "Sign in with OpenAI…",
        "sign_out": "Sign out",
        "signed_in_successfully": "Signed in successfully",
        "sonnet_week": "Sonnet · week",
        "spending_cap_reached": "spending cap reached",
        "spending_limit": "Spending limit",
        "the_session_is_stored_in_the": "The session is stored in the app's own keychain item. The app never reads Claude Code's credentials, so macOS won't ask for keychain access.",
        "today": "Today",
        "todays_cost_total": "Today's cost (total)",
        "token_counts_come_from_local_codex": "Token counts come from local Codex CLI sessions (~/.codex/sessions). Plan limits are fetched live from chatgpt.com using your OpenAI session.",
        "unauthorized_sign_in_again": "unauthorized — sign in again",
        "unexpected_json": "unexpected JSON",
        "unlimited": "Unlimited",
        "updated_at": "Updated at %@",
        "usage_limit_reached": "usage limit reached",
        "used": "Used",
        "used_2": "used",
        "waiting_for_authorization": "Waiting for authorization…",
        "waiting_for_browser_authorization": "Waiting for browser authorization…",
        "week": "Week",
        "workspace_owner_credits_depleted": "workspace owner credits depleted",
        "workspace_usage_limit_reached": "workspace usage limit reached",
        "you_can_close_this_tab_and": "You can close this tab and return to AI Usage.",
        "your_browser_will_open_to_authorize": "Your browser will open to authorize access with your Claude account (the same flow Claude Code uses). Once you approve, the app receives the authorization automatically.",
        "your_browser_will_open_to_authorize_2": "Your browser will open to authorize access with your OpenAI/ChatGPT account (the same flow Codex CLI uses). Once you approve, the app receives the authorization automatically.",
        "your_usage_limit_was_reached": "your usage limit was reached",
        "your_workspace_credits_are_depleted": "your workspace credits are depleted",
    ]

    private static let fr: [String: String] = [
        "unknown_error": "Erreur inconnue",
        "plan_badge": "Forfait %@",
        "balance": "Solde",
        "add_deepseek_key_in_settings": "Ajoutez votre clé API DeepSeek dans les réglages.",
        "balance_depleted": "Solde épuisé",
        "deepseek_caption": "Crédits prépayés de l'API DeepSeek. La clé est stockée dans le trousseau et ne sert qu'à lire votre solde.",
        "invalid_api_key": "Clé API invalide",
        "no_opencode_data": "Aucune donnée OpenCode",
        "open_settings": "Ouvrir les réglages",
        "opencode_caption": "Tokens et coût lus depuis la base de données locale d'OpenCode. OpenCode n'a pas de forfait, donc aucun pourcentage.",
        "paste_api_key": "Collez votre clé API…",
        "save": "Enregistrer",
        "turns_in_30_days": "%d tours sur 30 jours",
        "account": "Compte",
        "active": "Active",
        "apps_week": "Apps · semaine",
        "authorize_in_the_browser_and_paste": "Autorisez dans le navigateur et collez ci-dessous le code affiché.",
        "authorized": "Autorisé",
        "automatic_claude_first": "Automatique (Claude d'abord)",
        "by_model_last_30_days": "Par modèle (30 derniers jours)",
        "cache": "Cache",
        "cache_2": "cache",
        "cancel": "Annuler",
        "close": "Fermer",
        "code_state": "code#état",
        "codex_cli_detected": "Codex CLI détecté",
        "codex_cli_not_found": "Codex CLI introuvable",
        "connect": "Connecter",
        "connect_to": "Se connecter à %@",
        "copy_authorization_link": "Copier le lien d'autorisation",
        "cost": "Coût",
        "credits": "Crédits",
        "current_block_5_h": "Bloc actuel (5 h)",
        "days": "jours",
        "didnt_come_back_paste_the_code": "Ça ne revient pas tout seul ? Collez le code manuellement",
        "display": "Affichage",
        "ends_at": "se termine à %@",
        "ends_at_left": "se termine à %@ · %@ restants",
        "exchanging_the_code_for_a_session": "Échange du code contre la session…",
        "extra_usage_month": "Usage supplémentaire (mois)",
        "input": "Entrée",
        "input_2": "entrée",
        "invalid_response": "réponse invalide",
        "last_14_days": "14 derniers jours",
        "last_30_days": "30 derniers jours",
        "last_7_days": "7 derniers jours",
        "last_7_days_total": "7 derniers jours (total)",
        "left": "libre",
        "limit": "Limite",
        "limit_2": "limite",
        "limit_reached": "Limite atteinte : %@",
        "limits": "Limites : %@",
        "local_data": "Données locales",
        "menu_bar_shows": "La barre de menus affiche",
        "menu_sections": "Sections du menu",
        "messages": "Messages",
        "messages_2": "messages",
        "model": "Modèle",
        "no_codex_cli_sessions_found_in": "Aucune session Codex CLI trouvée dans ~/.codex.",
        "no_limit_data": "pas de données de limites",
        "no_recent_activity": "aucune activité récente",
        "no_session": "pas de session",
        "no_session_sign_in_with_your": "pas de session — connectez-vous avec votre compte Claude",
        "no_session_sign_in_with_your_2": "pas de session — connectez-vous avec votre compte OpenAI",
        "not_signed_in": "Non connectée",
        "of": "sur",
        "open_ai_usage": "Ouvrir AI Usage",
        "open_app": "Ouvrir l'app",
        "open_at_login": "Ouvrir à l'ouverture de session",
        "open_browser_to_authorize": "Ouvrir le navigateur pour autoriser",
        "opus_week": "Opus · semaine",
        "output": "Sortie",
        "output_2": "sortie",
        "plan_limits": "Limites du forfait",
        "port_is_busy_close_whatever_is": "le port %@ est occupé — fermez ce qui l'utilise (p. ex. un « codex login » en cours) et réessayez",
        "quit": "Quitter",
        "reading_usage_data": "Lecture des données d'utilisation…",
        "refresh_now": "Actualiser maintenant",
        "remaining": "Restant",
        "resets_in": "Se réinitialise dans %@ (%@)",
        "resets_on_at": "Se réinitialise le %@ à %@",
        "restore_default_order": "Restaurer l'ordre par défaut",
        "retry": "Réessayer",
        "session": "Session",
        "session_5_h": "Session (5 h)",
        "session_expired_sign_in_again": "session expirée — reconnectez-vous",
        "settings": "Réglages",
        "settings_2": "Réglages…",
        "show_limits_as": "Afficher les limites en",
        "sign_in_with": "Se connecter avec %@",
        "connect_with": "Se connecter à %@",
        "sign_in_with_claude": "Se connecter avec Claude…",
        "sign_in_with_openai": "Se connecter avec OpenAI…",
        "sign_out": "Se déconnecter",
        "signed_in_successfully": "Connexion réussie",
        "sonnet_week": "Sonnet · semaine",
        "spending_cap_reached": "plafond de dépenses atteint",
        "spending_limit": "Plafond de dépenses",
        "the_session_is_stored_in_the": "La session est enregistrée dans un élément de trousseau propre à l'app. L'app ne lit jamais les identifiants de Claude Code, macOS ne demandera donc aucun accès.",
        "today": "Aujourd'hui",
        "todays_cost_total": "Coût du jour (total)",
        "token_counts_come_from_local_codex": "Les tokens proviennent des sessions locales de Codex CLI (~/.codex/sessions). Les limites du forfait sont consultées en direct sur chatgpt.com avec votre session OpenAI.",
        "unauthorized_sign_in_again": "session non autorisée — reconnectez-vous",
        "unexpected_json": "JSON inattendu",
        "unlimited": "Illimités",
        "updated_at": "Mis à jour à %@",
        "usage_limit_reached": "limite d'utilisation atteinte",
        "used": "Consommé",
        "used_2": "utilisé",
        "waiting_for_authorization": "En attente d'autorisation…",
        "waiting_for_browser_authorization": "En attente de l'autorisation du navigateur…",
        "week": "Semaine",
        "workspace_owner_credits_depleted": "crédits du propriétaire du workspace épuisés",
        "workspace_usage_limit_reached": "limite d'utilisation du workspace atteinte",
        "you_can_close_this_tab_and": "Vous pouvez fermer cet onglet et revenir à AI Usage.",
        "your_browser_will_open_to_authorize": "Votre navigateur s'ouvrira pour autoriser l'accès avec votre compte Claude (le même flux que Claude Code). Une fois accepté, l'app recevra automatiquement l'autorisation.",
        "your_browser_will_open_to_authorize_2": "Votre navigateur s'ouvrira pour autoriser l'accès avec votre compte OpenAI/ChatGPT (le même flux que Codex CLI). Une fois accepté, l'app recevra automatiquement l'autorisation.",
        "your_usage_limit_was_reached": "limite d'utilisation de votre utilisateur atteinte",
        "your_workspace_credits_are_depleted": "crédits de votre utilisateur du workspace épuisés",
    ]

    private static let de: [String: String] = [
        "unknown_error": "Unbekannter Fehler",
        "plan_badge": "Tarif %@",
        "balance": "Guthaben",
        "add_deepseek_key_in_settings": "Füge deinen DeepSeek-API-Schlüssel in den Einstellungen hinzu.",
        "balance_depleted": "Guthaben aufgebraucht",
        "deepseek_caption": "Prepaid-Guthaben der DeepSeek-API. Der Schlüssel wird im Schlüsselbund gespeichert und liest nur dein Guthaben.",
        "invalid_api_key": "Ungültiger API-Schlüssel",
        "no_opencode_data": "Keine OpenCode-Daten",
        "open_settings": "Einstellungen öffnen",
        "opencode_caption": "Tokens und Kosten aus der lokalen OpenCode-Datenbank. OpenCode hat keinen Tarif, daher keine Prozentwerte.",
        "paste_api_key": "API-Schlüssel einfügen…",
        "save": "Speichern",
        "turns_in_30_days": "%d Turns in 30 Tagen",
        "account": "Konto",
        "active": "Aktiv",
        "apps_week": "Apps · Woche",
        "authorize_in_the_browser_and_paste": "Autorisiere im Browser und füge unten den angezeigten Code ein.",
        "authorized": "Autorisiert",
        "automatic_claude_first": "Automatisch (Claude zuerst)",
        "by_model_last_30_days": "Nach Modell (letzte 30 Tage)",
        "cache": "Cache",
        "cache_2": "Cache",
        "cancel": "Abbrechen",
        "close": "Schließen",
        "code_state": "Code#Status",
        "codex_cli_detected": "Codex CLI erkannt",
        "codex_cli_not_found": "Codex CLI nicht gefunden",
        "connect": "Verbinden",
        "connect_to": "Mit %@ verbinden",
        "copy_authorization_link": "Autorisierungslink kopieren",
        "cost": "Kosten",
        "credits": "Guthaben",
        "current_block_5_h": "Aktueller Block (5 Std.)",
        "days": "Tage",
        "didnt_come_back_paste_the_code": "Kommt nichts zurück? Füge den Code manuell ein",
        "display": "Darstellung",
        "ends_at": "endet um %@",
        "ends_at_left": "endet um %@ · noch %@",
        "exchanging_the_code_for_a_session": "Code wird gegen Sitzung getauscht…",
        "extra_usage_month": "Zusätzliche Nutzung (Monat)",
        "input": "Eingabe",
        "input_2": "Eingabe",
        "invalid_response": "ungültige Antwort",
        "last_14_days": "Letzte 14 Tage",
        "last_30_days": "Letzte 30 Tage",
        "last_7_days": "Letzte 7 Tage",
        "last_7_days_total": "Letzte 7 Tage (gesamt)",
        "left": "frei",
        "limit": "Limit",
        "limit_2": "Limit",
        "limit_reached": "Limit erreicht: %@",
        "limits": "Limits: %@",
        "local_data": "Lokale Daten",
        "menu_bar_shows": "Menüleiste zeigt",
        "menu_sections": "Menü-Abschnitte",
        "messages": "Nachrichten",
        "messages_2": "Nachrichten",
        "model": "Modell",
        "no_codex_cli_sessions_found_in": "Keine Codex-CLI-Sitzungen in ~/.codex gefunden.",
        "no_limit_data": "keine Limit-Daten",
        "no_recent_activity": "keine aktuelle Aktivität",
        "no_session": "keine Sitzung",
        "no_session_sign_in_with_your": "keine Sitzung — melde dich mit deinem Claude-Konto an",
        "no_session_sign_in_with_your_2": "keine Sitzung — melde dich mit deinem OpenAI-Konto an",
        "not_signed_in": "Nicht angemeldet",
        "of": "von",
        "open_ai_usage": "AI Usage öffnen",
        "open_app": "App öffnen",
        "open_at_login": "Beim Anmelden öffnen",
        "open_browser_to_authorize": "Browser zum Autorisieren öffnen",
        "opus_week": "Opus · Woche",
        "output": "Ausgabe",
        "output_2": "Ausgabe",
        "plan_limits": "Plan-Limits",
        "port_is_busy_close_whatever_is": "Port %@ ist belegt — schließe, was ihn belegt (z. B. ein laufendes „codex login“), und versuche es erneut",
        "quit": "Beenden",
        "reading_usage_data": "Nutzungsdaten werden gelesen…",
        "refresh_now": "Jetzt aktualisieren",
        "remaining": "Verbleibend",
        "resets_in": "Setzt sich in %@ zurück (%@)",
        "resets_on_at": "Setzt sich am %@ um %@ zurück",
        "restore_default_order": "Standardreihenfolge wiederherstellen",
        "retry": "Erneut versuchen",
        "session": "Sitzung",
        "session_5_h": "Sitzung (5 Std.)",
        "session_expired_sign_in_again": "Sitzung abgelaufen — melde dich erneut an",
        "settings": "Einstellungen",
        "settings_2": "Einstellungen…",
        "show_limits_as": "Limits anzeigen als",
        "sign_in_with": "Mit %@ anmelden",
        "connect_with": "Mit %@ verbinden",
        "sign_in_with_claude": "Mit Claude anmelden…",
        "sign_in_with_openai": "Mit OpenAI anmelden…",
        "sign_out": "Abmelden",
        "signed_in_successfully": "Erfolgreich angemeldet",
        "sonnet_week": "Sonnet · Woche",
        "spending_cap_reached": "Ausgabenlimit erreicht",
        "spending_limit": "Ausgabenlimit",
        "the_session_is_stored_in_the": "Die Sitzung wird in einem eigenen Schlüsselbund-Eintrag der App gespeichert. Die App liest nie die Zugangsdaten von Claude Code, daher fragt macOS nicht nach Zugriff.",
        "today": "Heute",
        "todays_cost_total": "Kosten heute (gesamt)",
        "token_counts_come_from_local_codex": "Die Token stammen aus den lokalen Codex-CLI-Sitzungen (~/.codex/sessions). Die Plan-Limits werden live über chatgpt.com mit deiner OpenAI-Sitzung abgefragt.",
        "unauthorized_sign_in_again": "Sitzung nicht autorisiert — melde dich erneut an",
        "unexpected_json": "Unerwartetes JSON",
        "unlimited": "Unbegrenzt",
        "updated_at": "Aktualisiert um %@",
        "usage_limit_reached": "Nutzungslimit erreicht",
        "used": "Verbraucht",
        "used_2": "belegt",
        "waiting_for_authorization": "Warte auf Autorisierung…",
        "waiting_for_browser_authorization": "Warte auf die Autorisierung im Browser…",
        "week": "Woche",
        "workspace_owner_credits_depleted": "Guthaben des Workspace-Inhabers aufgebraucht",
        "workspace_usage_limit_reached": "Nutzungslimit des Workspace erreicht",
        "you_can_close_this_tab_and": "Du kannst diesen Tab schließen und zu AI Usage zurückkehren.",
        "your_browser_will_open_to_authorize": "Der Browser öffnet sich, um den Zugriff mit deinem Claude-Konto zu autorisieren (derselbe Ablauf wie bei Claude Code). Nach der Bestätigung erhält die App die Autorisierung automatisch.",
        "your_browser_will_open_to_authorize_2": "Der Browser öffnet sich, um den Zugriff mit deinem OpenAI/ChatGPT-Konto zu autorisieren (derselbe Ablauf wie bei Codex CLI). Nach der Bestätigung erhält die App die Autorisierung automatisch.",
        "your_usage_limit_was_reached": "Nutzungslimit deines Nutzers erreicht",
        "your_workspace_credits_are_depleted": "Guthaben deines Workspace-Nutzers aufgebraucht",
    ]

    private static let it: [String: String] = [
        "unknown_error": "Errore sconosciuto",
        "plan_badge": "Piano %@",
        "balance": "Saldo",
        "add_deepseek_key_in_settings": "Aggiungi la tua chiave API DeepSeek nelle impostazioni.",
        "balance_depleted": "Saldo esaurito",
        "deepseek_caption": "Crediti prepagati dell'API DeepSeek. La chiave è salvata nel portachiavi e legge solo il saldo.",
        "invalid_api_key": "Chiave API non valida",
        "no_opencode_data": "Nessun dato OpenCode",
        "open_settings": "Apri impostazioni",
        "opencode_caption": "Token e costo letti dal database locale di OpenCode. OpenCode non ha un piano, quindi niente percentuali.",
        "paste_api_key": "Incolla la tua chiave API…",
        "save": "Salva",
        "turns_in_30_days": "%d turni in 30 giorni",
        "account": "Account",
        "active": "Attiva",
        "apps_week": "App · settimana",
        "authorize_in_the_browser_and_paste": "Autorizza nel browser e incolla qui sotto il codice mostrato.",
        "authorized": "Autorizzato",
        "automatic_claude_first": "Automatico (prima Claude)",
        "by_model_last_30_days": "Per modello (ultimi 30 giorni)",
        "cache": "Cache",
        "cache_2": "cache",
        "cancel": "Annulla",
        "close": "Chiudi",
        "code_state": "codice#stato",
        "codex_cli_detected": "Codex CLI rilevato",
        "codex_cli_not_found": "Codex CLI non trovato",
        "connect": "Connetti",
        "connect_to": "Connetti a %@",
        "copy_authorization_link": "Copia link di autorizzazione",
        "cost": "Costo",
        "credits": "Crediti",
        "current_block_5_h": "Blocco attuale (5 h)",
        "days": "giorni",
        "didnt_come_back_paste_the_code": "Non torna da solo? Incolla il codice manualmente",
        "display": "Visualizzazione",
        "ends_at": "termina alle %@",
        "ends_at_left": "termina alle %@ · mancano %@",
        "exchanging_the_code_for_a_session": "Scambio del codice con la sessione…",
        "extra_usage_month": "Utilizzo extra (mese)",
        "input": "Input",
        "input_2": "input",
        "invalid_response": "risposta non valida",
        "last_14_days": "Ultimi 14 giorni",
        "last_30_days": "Ultimi 30 giorni",
        "last_7_days": "Ultimi 7 giorni",
        "last_7_days_total": "Ultimi 7 giorni (totale)",
        "left": "libero",
        "limit": "Limite",
        "limit_2": "limite",
        "limit_reached": "Limite raggiunto: %@",
        "limits": "Limiti: %@",
        "local_data": "Dati locali",
        "menu_bar_shows": "La barra dei menu mostra",
        "menu_sections": "Sezioni del menu",
        "messages": "Messaggi",
        "messages_2": "messaggi",
        "model": "Modello",
        "no_codex_cli_sessions_found_in": "Nessuna sessione Codex CLI trovata in ~/.codex.",
        "no_limit_data": "nessun dato sui limiti",
        "no_recent_activity": "nessuna attività recente",
        "no_session": "nessuna sessione",
        "no_session_sign_in_with_your": "nessuna sessione — accedi con il tuo account Claude",
        "no_session_sign_in_with_your_2": "nessuna sessione — accedi con il tuo account OpenAI",
        "not_signed_in": "Non connessa",
        "of": "di",
        "open_ai_usage": "Apri AI Usage",
        "open_app": "Apri l'app",
        "open_at_login": "Apri all'accesso",
        "open_browser_to_authorize": "Apri il browser per autorizzare",
        "opus_week": "Opus · settimana",
        "output": "Output",
        "output_2": "output",
        "plan_limits": "Limiti del piano",
        "port_is_busy_close_whatever_is": "la porta %@ è occupata — chiudi ciò che la usa (ad es. un 'codex login' in corso) e riprova",
        "quit": "Esci",
        "reading_usage_data": "Lettura dei dati di utilizzo…",
        "refresh_now": "Aggiorna ora",
        "remaining": "Rimanente",
        "resets_in": "Si azzera tra %@ (%@)",
        "resets_on_at": "Si azzera il %@ alle %@",
        "restore_default_order": "Ripristina ordine predefinito",
        "retry": "Riprova",
        "session": "Sessione",
        "session_5_h": "Sessione (5 h)",
        "session_expired_sign_in_again": "sessione scaduta — accedi di nuovo",
        "settings": "Impostazioni",
        "settings_2": "Impostazioni…",
        "show_limits_as": "Mostra i limiti come",
        "sign_in_with": "Accedi con %@",
        "connect_with": "Connetti a %@",
        "sign_in_with_claude": "Accedi con Claude…",
        "sign_in_with_openai": "Accedi con OpenAI…",
        "sign_out": "Disconnetti",
        "signed_in_successfully": "Accesso riuscito",
        "sonnet_week": "Sonnet · settimana",
        "spending_cap_reached": "tetto di spesa raggiunto",
        "spending_limit": "Limite di spesa",
        "the_session_is_stored_in_the": "La sessione è salvata in un elemento del portachiavi dell'app. L'app non legge mai le credenziali di Claude Code, quindi macOS non chiederà l'accesso.",
        "today": "Oggi",
        "todays_cost_total": "Costo di oggi (totale)",
        "token_counts_come_from_local_codex": "I token provengono dalle sessioni locali di Codex CLI (~/.codex/sessions). I limiti del piano vengono letti in tempo reale da chatgpt.com con la tua sessione OpenAI.",
        "unauthorized_sign_in_again": "sessione non autorizzata — accedi di nuovo",
        "unexpected_json": "JSON imprevisto",
        "unlimited": "Illimitati",
        "updated_at": "Aggiornato alle %@",
        "usage_limit_reached": "limite di utilizzo raggiunto",
        "used": "Consumato",
        "used_2": "usato",
        "waiting_for_authorization": "In attesa di autorizzazione…",
        "waiting_for_browser_authorization": "In attesa dell'autorizzazione dal browser…",
        "week": "Settimana",
        "workspace_owner_credits_depleted": "crediti del proprietario del workspace esauriti",
        "workspace_usage_limit_reached": "limite di utilizzo del workspace raggiunto",
        "you_can_close_this_tab_and": "Puoi chiudere questa scheda e tornare ad AI Usage.",
        "your_browser_will_open_to_authorize": "Si aprirà il browser per autorizzare l'accesso con il tuo account Claude (lo stesso flusso di Claude Code). Dopo l'approvazione, l'app riceverà automaticamente l'autorizzazione.",
        "your_browser_will_open_to_authorize_2": "Si aprirà il browser per autorizzare l'accesso con il tuo account OpenAI/ChatGPT (lo stesso flusso di Codex CLI). Dopo l'approvazione, l'app riceverà automaticamente l'autorizzazione.",
        "your_usage_limit_was_reached": "limite di utilizzo del tuo utente raggiunto",
        "your_workspace_credits_are_depleted": "crediti del tuo utente del workspace esauriti",
    ]

    private static let pt: [String: String] = [
        "unknown_error": "Erro desconhecido",
        "plan_badge": "Plano %@",
        "balance": "Saldo",
        "add_deepseek_key_in_settings": "Adiciona a tua chave de API DeepSeek nas definições.",
        "balance_depleted": "Saldo esgotado",
        "deepseek_caption": "Créditos pré-pagos da API DeepSeek. A chave é guardada no porta-chaves e só consulta o saldo.",
        "invalid_api_key": "Chave de API inválida",
        "no_opencode_data": "Sem dados do OpenCode",
        "open_settings": "Abrir definições",
        "opencode_caption": "Tokens e custo lidos da base de dados local do OpenCode. O OpenCode não tem plano, por isso não há percentagens.",
        "paste_api_key": "Cola a tua chave de API…",
        "save": "Guardar",
        "turns_in_30_days": "%d turnos em 30 dias",
        "account": "Conta",
        "active": "Ativa",
        "apps_week": "Apps · semana",
        "authorize_in_the_browser_and_paste": "Autoriza no navegador e cola abaixo o código mostrado.",
        "authorized": "Autorizado",
        "automatic_claude_first": "Automático (Claude primeiro)",
        "by_model_last_30_days": "Por modelo (últimos 30 dias)",
        "cache": "Cache",
        "cache_2": "cache",
        "cancel": "Cancelar",
        "close": "Fechar",
        "code_state": "código#estado",
        "codex_cli_detected": "Codex CLI detetado",
        "codex_cli_not_found": "Codex CLI não encontrado",
        "connect": "Ligar",
        "connect_to": "Ligar a %@",
        "copy_authorization_link": "Copiar link de autorização",
        "cost": "Custo",
        "credits": "Créditos",
        "current_block_5_h": "Bloco atual (5 h)",
        "days": "dias",
        "didnt_come_back_paste_the_code": "Não volta sozinho? Cola o código manualmente",
        "display": "Visualização",
        "ends_at": "termina às %@",
        "ends_at_left": "termina às %@ · faltam %@",
        "exchanging_the_code_for_a_session": "A trocar o código pela sessão…",
        "extra_usage_month": "Utilização extra (mês)",
        "input": "Entrada",
        "input_2": "entrada",
        "invalid_response": "resposta inválida",
        "last_14_days": "Últimos 14 dias",
        "last_30_days": "Últimos 30 dias",
        "last_7_days": "Últimos 7 dias",
        "last_7_days_total": "Últimos 7 dias (total)",
        "left": "livre",
        "limit": "Limite",
        "limit_2": "limite",
        "limit_reached": "Limite atingido: %@",
        "limits": "Limites: %@",
        "local_data": "Dados locais",
        "menu_bar_shows": "A barra de menus mostra",
        "menu_sections": "Secções do menu",
        "messages": "Mensagens",
        "messages_2": "mensagens",
        "model": "Modelo",
        "no_codex_cli_sessions_found_in": "Não foram encontradas sessões do Codex CLI em ~/.codex.",
        "no_limit_data": "sem dados de limites",
        "no_recent_activity": "sem atividade recente",
        "no_session": "sem sessão",
        "no_session_sign_in_with_your": "sem sessão — inicia sessão com a tua conta Claude",
        "no_session_sign_in_with_your_2": "sem sessão — inicia sessão com a tua conta OpenAI",
        "not_signed_in": "Não iniciada",
        "of": "de",
        "open_ai_usage": "Abrir AI Usage",
        "open_app": "Abrir a app",
        "open_at_login": "Abrir ao iniciar sessão",
        "open_browser_to_authorize": "Abrir navegador para autorizar",
        "opus_week": "Opus · semana",
        "output": "Saída",
        "output_2": "saída",
        "plan_limits": "Limites do plano",
        "port_is_busy_close_whatever_is": "a porta %@ está ocupada — fecha o que a está a usar (p. ex. um 'codex login' pendente) e tenta novamente",
        "quit": "Sair",
        "reading_usage_data": "A ler dados de utilização…",
        "refresh_now": "Atualizar agora",
        "remaining": "Restante",
        "resets_in": "Reinicia em %@ (%@)",
        "resets_on_at": "Reinicia a %@ às %@",
        "restore_default_order": "Repor ordem predefinida",
        "retry": "Tentar novamente",
        "session": "Sessão",
        "session_5_h": "Sessão (5 h)",
        "session_expired_sign_in_again": "sessão expirada — inicia sessão novamente",
        "settings": "Definições",
        "settings_2": "Definições…",
        "show_limits_as": "Mostrar limites como",
        "sign_in_with": "Iniciar sessão com %@",
        "connect_with": "Conectar a %@",
        "sign_in_with_claude": "Iniciar sessão com Claude…",
        "sign_in_with_openai": "Iniciar sessão com OpenAI…",
        "sign_out": "Terminar sessão",
        "signed_in_successfully": "Sessão iniciada com sucesso",
        "sonnet_week": "Sonnet · semana",
        "spending_cap_reached": "teto de gastos atingido",
        "spending_limit": "Limite de gastos",
        "the_session_is_stored_in_the": "A sessão é guardada num item próprio das Porta-chaves. A app nunca lê as credenciais do Claude Code, pelo que o macOS não pedirá acesso.",
        "today": "Hoje",
        "todays_cost_total": "Custo de hoje (total)",
        "token_counts_come_from_local_codex": "Os tokens vêm das sessões locais do Codex CLI (~/.codex/sessions). Os limites do plano são consultados em direto em chatgpt.com com a tua sessão OpenAI.",
        "unauthorized_sign_in_again": "sessão não autorizada — inicia sessão novamente",
        "unexpected_json": "JSON inesperado",
        "unlimited": "Ilimitados",
        "updated_at": "Atualizado às %@",
        "usage_limit_reached": "limite de utilização atingido",
        "used": "Consumido",
        "used_2": "usado",
        "waiting_for_authorization": "A aguardar autorização…",
        "waiting_for_browser_authorization": "A aguardar a autorização do navegador…",
        "week": "Semana",
        "workspace_owner_credits_depleted": "créditos do proprietário do workspace esgotados",
        "workspace_usage_limit_reached": "limite de utilização do workspace atingido",
        "you_can_close_this_tab_and": "Já podes fechar este separador e voltar ao AI Usage.",
        "your_browser_will_open_to_authorize": "O navegador vai abrir para autorizar o acesso com a tua conta Claude (o mesmo fluxo do Claude Code). Ao aceitar, a app recebe a autorização automaticamente.",
        "your_browser_will_open_to_authorize_2": "O navegador vai abrir para autorizar o acesso com a tua conta OpenAI/ChatGPT (o mesmo fluxo do Codex CLI). Ao aceitar, a app recebe a autorização automaticamente.",
        "your_usage_limit_was_reached": "limite de utilização do teu utilizador atingido",
        "your_workspace_credits_are_depleted": "créditos do teu utilizador do workspace esgotados",
    ]

    private static let ja: [String: String] = [
        "unknown_error": "不明なエラー",
        "plan_badge": "%@ プラン",
        "balance": "残高",
        "add_deepseek_key_in_settings": "設定でDeepSeek APIキーを追加してください。",
        "balance_depleted": "残高がありません",
        "deepseek_caption": "DeepSeek APIのプリペイド残高です。キーはキーチェーンに保存され、残高の確認のみに使われます。",
        "invalid_api_key": "無効なAPIキー",
        "no_opencode_data": "OpenCodeのデータがありません",
        "open_settings": "設定を開く",
        "opencode_caption": "OpenCodeのローカルデータベースから読み取ったトークンとコスト。OpenCodeにはプランがないため、パーセンテージはありません。",
        "paste_api_key": "APIキーを貼り付け…",
        "save": "保存",
        "turns_in_30_days": "過去30日間で%dターン",
        "account": "アカウント",
        "active": "有効",
        "apps_week": "アプリ · 週",
        "authorize_in_the_browser_and_paste": "ブラウザで認証し、表示されたコードを下に貼り付けてください。",
        "authorized": "認証されました",
        "automatic_claude_first": "自動（Claude優先）",
        "by_model_last_30_days": "モデル別（過去30日）",
        "cache": "キャッシュ",
        "cache_2": "キャッシュ",
        "cancel": "キャンセル",
        "close": "閉じる",
        "code_state": "コード#ステート",
        "codex_cli_detected": "Codex CLIを検出",
        "codex_cli_not_found": "Codex CLIが見つかりません",
        "connect": "接続",
        "connect_to": "%@ に接続",
        "copy_authorization_link": "認証リンクをコピー",
        "cost": "コスト",
        "credits": "クレジット",
        "current_block_5_h": "現在のブロック（5時間）",
        "days": "日",
        "didnt_come_back_paste_the_code": "自動で戻らない場合はコードを手動で貼り付け",
        "display": "表示",
        "ends_at": "%@ に終了",
        "ends_at_left": "%@ に終了 · 残り %@",
        "exchanging_the_code_for_a_session": "コードをセッションと交換中…",
        "extra_usage_month": "追加使用（月）",
        "input": "入力",
        "input_2": "入力",
        "invalid_response": "無効な応答",
        "last_14_days": "過去14日",
        "last_30_days": "過去30日",
        "last_7_days": "過去7日",
        "last_7_days_total": "過去7日（合計）",
        "left": "残り",
        "limit": "上限",
        "limit_2": "上限",
        "limit_reached": "上限に達しました：%@",
        "limits": "上限：%@",
        "local_data": "ローカルデータ",
        "menu_bar_shows": "メニューバーの表示",
        "menu_sections": "メニューのセクション",
        "messages": "メッセージ",
        "messages_2": "メッセージ",
        "model": "モデル",
        "no_codex_cli_sessions_found_in": "~/.codex にCodex CLIのセッションが見つかりません。",
        "no_limit_data": "上限データなし",
        "no_recent_activity": "最近のアクティビティなし",
        "no_session": "セッションなし",
        "no_session_sign_in_with_your": "セッションなし — Claudeアカウントでサインインしてください",
        "no_session_sign_in_with_your_2": "セッションなし — OpenAIアカウントでサインインしてください",
        "not_signed_in": "未ログイン",
        "of": "/",
        "open_ai_usage": "AI Usageを開く",
        "open_app": "アプリを開く",
        "open_at_login": "ログイン時に開く",
        "open_browser_to_authorize": "ブラウザで認証する",
        "opus_week": "Opus · 週",
        "output": "出力",
        "output_2": "出力",
        "plan_limits": "プランの上限",
        "port_is_busy_close_whatever_is": "ポート%@が使用中です — 使用中のプロセス（例：進行中の codex login）を終了して再試行してください",
        "quit": "終了",
        "reading_usage_data": "使用データを読み込み中…",
        "refresh_now": "今すぐ更新",
        "remaining": "残り",
        "resets_in": "%@後にリセット（%@）",
        "resets_on_at": "%@ %@ にリセット",
        "restore_default_order": "デフォルトの順序に戻す",
        "retry": "再試行",
        "session": "セッション",
        "session_5_h": "セッション（5時間）",
        "session_expired_sign_in_again": "セッションの期限切れ — 再度サインインしてください",
        "settings": "設定",
        "settings_2": "設定…",
        "show_limits_as": "上限の表示方法",
        "sign_in_with": "%@ でサインイン",
        "connect_with": "%@ に接続",
        "sign_in_with_claude": "Claudeでサインイン…",
        "sign_in_with_openai": "OpenAIでサインイン…",
        "sign_out": "ログアウト",
        "signed_in_successfully": "サインインしました",
        "sonnet_week": "Sonnet · 週",
        "spending_cap_reached": "支出上限に達しました",
        "spending_limit": "支出上限",
        "the_session_is_stored_in_the": "セッションはアプリ専用のキーチェーン項目に保存されます。Claude Codeの認証情報は読み取らないため、macOSがアクセス許可を求めることはありません。",
        "today": "今日",
        "todays_cost_total": "今日のコスト（合計）",
        "token_counts_come_from_local_codex": "トークンはCodex CLIのローカルセッション（~/.codex/sessions）から取得します。プランの上限はOpenAIセッションを使ってchatgpt.comからリアルタイムに取得します。",
        "unauthorized_sign_in_again": "セッションが未認証 — 再度サインインしてください",
        "unexpected_json": "予期しないJSON",
        "unlimited": "無制限",
        "updated_at": "%@ に更新",
        "usage_limit_reached": "使用上限に達しました",
        "used": "使用済み",
        "used_2": "使用",
        "waiting_for_authorization": "認証を待っています…",
        "waiting_for_browser_authorization": "ブラウザでの認証を待っています…",
        "week": "週",
        "workspace_owner_credits_depleted": "ワークスペース所有者のクレジットが枯渇",
        "workspace_usage_limit_reached": "ワークスペースの使用上限に達しました",
        "you_can_close_this_tab_and": "このタブを閉じてAI Usageに戻れます。",
        "your_browser_will_open_to_authorize": "ブラウザが開き、Claudeアカウントでアクセスを認証します（Claude Codeと同じフロー）。承認すると、アプリは自動的に認証を受け取ります。",
        "your_browser_will_open_to_authorize_2": "ブラウザが開き、OpenAI/ChatGPTアカウントでアクセスを認証します（Codex CLIと同じフロー）。承認すると、アプリは自動的に認証を受け取ります。",
        "your_usage_limit_was_reached": "あなたの使用上限に達しました",
        "your_workspace_credits_are_depleted": "ワークスペースのあなたのクレジットが枯渇",
    ]

    private static let zh: [String: String] = [
        "unknown_error": "未知错误",
        "plan_badge": "%@ 套餐",
        "balance": "余额",
        "add_deepseek_key_in_settings": "在设置中添加你的 DeepSeek API 密钥。",
        "balance_depleted": "余额已用尽",
        "deepseek_caption": "DeepSeek API 的预付余额。密钥保存在钥匙串中，仅用于查询余额。",
        "invalid_api_key": "API 密钥无效",
        "no_opencode_data": "没有 OpenCode 数据",
        "open_settings": "打开设置",
        "opencode_caption": "从 OpenCode 的本地数据库读取的令牌和费用。OpenCode 没有套餐，因此没有百分比。",
        "paste_api_key": "粘贴你的 API 密钥…",
        "save": "保存",
        "turns_in_30_days": "30天内%d个回合",
        "account": "账户",
        "active": "有效",
        "apps_week": "应用 · 周",
        "authorize_in_the_browser_and_paste": "在浏览器中授权，然后将显示的代码粘贴到下方。",
        "authorized": "已授权",
        "automatic_claude_first": "自动（Claude 优先）",
        "by_model_last_30_days": "按模型（最近 30 天）",
        "cache": "缓存",
        "cache_2": "缓存",
        "cancel": "取消",
        "close": "关闭",
        "code_state": "代码#状态",
        "codex_cli_detected": "已检测到 Codex CLI",
        "codex_cli_not_found": "未找到 Codex CLI",
        "connect": "连接",
        "connect_to": "连接 %@",
        "copy_authorization_link": "复制授权链接",
        "cost": "成本",
        "credits": "额度",
        "current_block_5_h": "当前时段（5 小时）",
        "days": "天",
        "didnt_come_back_paste_the_code": "没有自动返回？手动粘贴代码",
        "display": "显示",
        "ends_at": "%@ 结束",
        "ends_at_left": "%@ 结束 · 剩余 %@",
        "exchanging_the_code_for_a_session": "正在用代码换取会话…",
        "extra_usage_month": "额外用量（月）",
        "input": "输入",
        "input_2": "输入",
        "invalid_response": "无效响应",
        "last_14_days": "最近 14 天",
        "last_30_days": "最近 30 天",
        "last_7_days": "最近 7 天",
        "last_7_days_total": "最近 7 天（总计）",
        "left": "剩余",
        "limit": "限额",
        "limit_2": "限额",
        "limit_reached": "已达上限：%@",
        "limits": "限额：%@",
        "local_data": "本地数据",
        "menu_bar_shows": "菜单栏显示",
        "menu_sections": "菜单栏目",
        "messages": "消息",
        "messages_2": "条消息",
        "model": "模型",
        "no_codex_cli_sessions_found_in": "在 ~/.codex 中未找到 Codex CLI 会话。",
        "no_limit_data": "无限额数据",
        "no_recent_activity": "近期无活动",
        "no_session": "无会话",
        "no_session_sign_in_with_your": "无会话 — 请使用 Claude 账户登录",
        "no_session_sign_in_with_your_2": "无会话 — 请使用 OpenAI 账户登录",
        "not_signed_in": "未登录",
        "of": "/",
        "open_ai_usage": "打开 AI Usage",
        "open_app": "打开应用",
        "open_at_login": "登录时打开",
        "open_browser_to_authorize": "打开浏览器进行授权",
        "opus_week": "Opus · 周",
        "output": "输出",
        "output_2": "输出",
        "plan_limits": "套餐限额",
        "port_is_busy_close_whatever_is": "端口 %@ 被占用 — 请关闭占用它的程序（例如未完成的 codex login）后重试",
        "quit": "退出",
        "reading_usage_data": "正在读取使用数据…",
        "refresh_now": "立即刷新",
        "remaining": "剩余",
        "resets_in": "%@后重置（%@）",
        "resets_on_at": "将于 %@ %@ 重置",
        "restore_default_order": "恢复默认顺序",
        "retry": "重试",
        "session": "会话",
        "session_5_h": "会话（5 小时）",
        "session_expired_sign_in_again": "会话已过期 — 请重新登录",
        "settings": "设置",
        "settings_2": "设置…",
        "show_limits_as": "限额显示为",
        "sign_in_with": "使用 %@ 登录",
        "connect_with": "连接到 %@",
        "sign_in_with_claude": "使用 Claude 登录…",
        "sign_in_with_openai": "使用 OpenAI 登录…",
        "sign_out": "退出登录",
        "signed_in_successfully": "登录成功",
        "sonnet_week": "Sonnet · 周",
        "spending_cap_reached": "已达支出上限",
        "spending_limit": "支出限额",
        "the_session_is_stored_in_the": "会话保存在应用自己的钥匙串项中。应用不会读取 Claude Code 的凭据，因此 macOS 不会请求访问权限。",
        "today": "今天",
        "todays_cost_total": "今日成本（总计）",
        "token_counts_come_from_local_codex": "Token 数据来自 Codex CLI 的本地会话（~/.codex/sessions）。套餐限额通过你的 OpenAI 会话从 chatgpt.com 实时获取。",
        "unauthorized_sign_in_again": "会话未授权 — 请重新登录",
        "unexpected_json": "意外的 JSON",
        "unlimited": "无限",
        "updated_at": "更新于 %@",
        "usage_limit_reached": "已达使用上限",
        "used": "已用",
        "used_2": "已用",
        "waiting_for_authorization": "等待授权…",
        "waiting_for_browser_authorization": "等待浏览器授权…",
        "week": "周",
        "workspace_owner_credits_depleted": "工作区所有者的额度已用尽",
        "workspace_usage_limit_reached": "已达工作区使用上限",
        "you_can_close_this_tab_and": "现在可以关闭此标签页并返回 AI Usage。",
        "your_browser_will_open_to_authorize": "浏览器将打开以使用你的 Claude 账户授权（与 Claude Code 相同的流程）。同意后，应用会自动收到授权。",
        "your_browser_will_open_to_authorize_2": "浏览器将打开以使用你的 OpenAI/ChatGPT 账户授权（与 Codex CLI 相同的流程）。同意后，应用会自动收到授权。",
        "your_usage_limit_was_reached": "已达你的使用上限",
        "your_workspace_credits_are_depleted": "你的工作区额度已用尽",
    ]

    private static let ko: [String: String] = [
        "unknown_error": "알 수 없는 오류",
        "plan_badge": "%@ 요금제",
        "balance": "잔액",
        "add_deepseek_key_in_settings": "설정에서 DeepSeek API 키를 추가하세요.",
        "balance_depleted": "잔액 소진",
        "deepseek_caption": "DeepSeek API의 선불 크레딧입니다. 키는 키체인에 저장되며 잔액 조회에만 사용됩니다.",
        "invalid_api_key": "잘못된 API 키",
        "no_opencode_data": "OpenCode 데이터 없음",
        "open_settings": "설정 열기",
        "opencode_caption": "OpenCode의 로컬 데이터베이스에서 읽은 토큰과 비용입니다. OpenCode에는 플랜이 없어 백분율이 없습니다.",
        "paste_api_key": "API 키 붙여넣기…",
        "save": "저장",
        "turns_in_30_days": "30일간 %d턴",
        "account": "계정",
        "active": "활성",
        "apps_week": "앱 · 주간",
        "authorize_in_the_browser_and_paste": "브라우저에서 인증한 후 표시된 코드를 아래에 붙여넣으세요.",
        "authorized": "인증 완료",
        "automatic_claude_first": "자동 (Claude 우선)",
        "by_model_last_30_days": "모델별 (최근 30일)",
        "cache": "캐시",
        "cache_2": "캐시",
        "cancel": "취소",
        "close": "닫기",
        "code_state": "코드#상태",
        "codex_cli_detected": "Codex CLI 감지됨",
        "codex_cli_not_found": "Codex CLI를 찾을 수 없음",
        "connect": "연결",
        "connect_to": "%@ 연결",
        "copy_authorization_link": "인증 링크 복사",
        "cost": "비용",
        "credits": "크레딧",
        "current_block_5_h": "현재 블록 (5시간)",
        "days": "일",
        "didnt_come_back_paste_the_code": "자동으로 돌아오지 않나요? 코드를 직접 붙여넣기",
        "display": "표시",
        "ends_at": "%@ 종료",
        "ends_at_left": "%@ 종료 · %@ 남음",
        "exchanging_the_code_for_a_session": "코드를 세션으로 교환 중…",
        "extra_usage_month": "추가 사용량 (월)",
        "input": "입력",
        "input_2": "입력",
        "invalid_response": "잘못된 응답",
        "last_14_days": "최근 14일",
        "last_30_days": "최근 30일",
        "last_7_days": "최근 7일",
        "last_7_days_total": "최근 7일 (합계)",
        "left": "남음",
        "limit": "한도",
        "limit_2": "한도",
        "limit_reached": "한도 도달: %@",
        "limits": "한도: %@",
        "local_data": "로컬 데이터",
        "menu_bar_shows": "메뉴 막대 표시",
        "menu_sections": "메뉴 섹션",
        "messages": "메시지",
        "messages_2": "메시지",
        "model": "모델",
        "no_codex_cli_sessions_found_in": "~/.codex에서 Codex CLI 세션을 찾을 수 없습니다.",
        "no_limit_data": "한도 데이터 없음",
        "no_recent_activity": "최근 활동 없음",
        "no_session": "세션 없음",
        "no_session_sign_in_with_your": "세션 없음 — Claude 계정으로 로그인하세요",
        "no_session_sign_in_with_your_2": "세션 없음 — OpenAI 계정으로 로그인하세요",
        "not_signed_in": "로그인 안 됨",
        "of": "/",
        "open_ai_usage": "AI Usage 열기",
        "open_app": "앱 열기",
        "open_at_login": "로그인 시 열기",
        "open_browser_to_authorize": "브라우저에서 인증하기",
        "opus_week": "Opus · 주간",
        "output": "출력",
        "output_2": "출력",
        "plan_limits": "플랜 한도",
        "port_is_busy_close_whatever_is": "포트 %@이(가) 사용 중입니다 — 사용 중인 프로세스(예: 진행 중인 codex login)를 종료하고 다시 시도하세요",
        "quit": "종료",
        "reading_usage_data": "사용 데이터 읽는 중…",
        "refresh_now": "지금 새로고침",
        "remaining": "남은 양",
        "resets_in": "%@ 후 초기화 (%@)",
        "resets_on_at": "%@ %@에 초기화",
        "restore_default_order": "기본 순서 복원",
        "retry": "다시 시도",
        "session": "세션",
        "session_5_h": "세션 (5시간)",
        "session_expired_sign_in_again": "세션 만료 — 다시 로그인하세요",
        "settings": "설정",
        "settings_2": "설정…",
        "show_limits_as": "한도 표시 방식",
        "sign_in_with": "%@ 로그인",
        "connect_with": "%@에 연결",
        "sign_in_with_claude": "Claude 로그인…",
        "sign_in_with_openai": "OpenAI 로그인…",
        "sign_out": "로그아웃",
        "signed_in_successfully": "로그인 성공",
        "sonnet_week": "Sonnet · 주간",
        "spending_cap_reached": "지출 상한 도달",
        "spending_limit": "지출 한도",
        "the_session_is_stored_in_the": "세션은 앱 전용 키체인 항목에 저장됩니다. 앱은 Claude Code의 자격 증명을 읽지 않으므로 macOS가 접근 권한을 요청하지 않습니다.",
        "today": "오늘",
        "todays_cost_total": "오늘 비용 (합계)",
        "token_counts_come_from_local_codex": "토큰은 Codex CLI 로컬 세션(~/.codex/sessions)에서 가져옵니다. 플랜 한도는 OpenAI 세션으로 chatgpt.com에서 실시간 조회합니다.",
        "unauthorized_sign_in_again": "세션 인증 안 됨 — 다시 로그인하세요",
        "unexpected_json": "예기치 않은 JSON",
        "unlimited": "무제한",
        "updated_at": "%@에 업데이트됨",
        "usage_limit_reached": "사용 한도 도달",
        "used": "사용량",
        "used_2": "사용",
        "waiting_for_authorization": "인증 대기 중…",
        "waiting_for_browser_authorization": "브라우저 인증 대기 중…",
        "week": "주간",
        "workspace_owner_credits_depleted": "워크스페이스 소유자 크레딧 소진",
        "workspace_usage_limit_reached": "워크스페이스 사용 한도 도달",
        "you_can_close_this_tab_and": "이 탭을 닫고 AI Usage로 돌아가세요.",
        "your_browser_will_open_to_authorize": "브라우저가 열리고 Claude 계정으로 접근을 인증합니다(Claude Code와 동일한 방식). 승인하면 앱이 자동으로 인증을 받습니다.",
        "your_browser_will_open_to_authorize_2": "브라우저가 열리고 OpenAI/ChatGPT 계정으로 접근을 인증합니다(Codex CLI와 동일한 방식). 승인하면 앱이 자동으로 인증을 받습니다.",
        "your_usage_limit_was_reached": "내 사용 한도 도달",
        "your_workspace_credits_are_depleted": "워크스페이스 내 크레딧 소진",
    ]

    private static let ru: [String: String] = [
        "unknown_error": "Неизвестная ошибка",
        "plan_badge": "Тариф %@",
        "balance": "Баланс",
        "add_deepseek_key_in_settings": "Добавьте API-ключ DeepSeek в настройках.",
        "balance_depleted": "Баланс исчерпан",
        "deepseek_caption": "Предоплаченные кредиты API DeepSeek. Ключ хранится в связке ключей и используется только для проверки баланса.",
        "invalid_api_key": "Неверный API-ключ",
        "no_opencode_data": "Нет данных OpenCode",
        "open_settings": "Открыть настройки",
        "opencode_caption": "Токены и стоимость из локальной базы данных OpenCode. У OpenCode нет тарифа, поэтому процентов нет.",
        "paste_api_key": "Вставьте API-ключ…",
        "save": "Сохранить",
        "turns_in_30_days": "%d ходов за 30 дней",
        "account": "Аккаунт",
        "active": "Активна",
        "apps_week": "Приложения · неделя",
        "authorize_in_the_browser_and_paste": "Авторизуйтесь в браузере и вставьте показанный код ниже.",
        "authorized": "Авторизовано",
        "automatic_claude_first": "Автоматически (сначала Claude)",
        "by_model_last_30_days": "По моделям (последние 30 дней)",
        "cache": "Кэш",
        "cache_2": "кэш",
        "cancel": "Отмена",
        "close": "Закрыть",
        "code_state": "код#состояние",
        "codex_cli_detected": "Codex CLI обнаружен",
        "codex_cli_not_found": "Codex CLI не найден",
        "connect": "Подключить",
        "connect_to": "Подключить %@",
        "copy_authorization_link": "Скопировать ссылку авторизации",
        "cost": "Стоимость",
        "credits": "Кредиты",
        "current_block_5_h": "Текущий блок (5 ч)",
        "days": "дней",
        "didnt_come_back_paste_the_code": "Не вернулось само? Вставьте код вручную",
        "display": "Отображение",
        "ends_at": "заканчивается в %@",
        "ends_at_left": "заканчивается в %@ · осталось %@",
        "exchanging_the_code_for_a_session": "Обмен кода на сессию…",
        "extra_usage_month": "Доп. использование (месяц)",
        "input": "Ввод",
        "input_2": "ввод",
        "invalid_response": "недопустимый ответ",
        "last_14_days": "Последние 14 дней",
        "last_30_days": "Последние 30 дней",
        "last_7_days": "Последние 7 дней",
        "last_7_days_total": "Последние 7 дней (всего)",
        "left": "свободно",
        "limit": "Лимит",
        "limit_2": "лимит",
        "limit_reached": "Лимит достигнут: %@",
        "limits": "Лимиты: %@",
        "local_data": "Локальные данные",
        "menu_bar_shows": "В строке меню показывать",
        "menu_sections": "Разделы меню",
        "messages": "Сообщения",
        "messages_2": "сообщений",
        "model": "Модель",
        "no_codex_cli_sessions_found_in": "Сессии Codex CLI в ~/.codex не найдены.",
        "no_limit_data": "нет данных о лимитах",
        "no_recent_activity": "нет недавней активности",
        "no_session": "нет сессии",
        "no_session_sign_in_with_your": "нет сессии — войдите с аккаунтом Claude",
        "no_session_sign_in_with_your_2": "нет сессии — войдите с аккаунтом OpenAI",
        "not_signed_in": "Вход не выполнен",
        "of": "из",
        "open_ai_usage": "Открыть AI Usage",
        "open_app": "Открыть приложение",
        "open_at_login": "Открывать при входе в систему",
        "open_browser_to_authorize": "Открыть браузер для авторизации",
        "opus_week": "Opus · неделя",
        "output": "Вывод",
        "output_2": "вывод",
        "plan_limits": "Лимиты тарифа",
        "port_is_busy_close_whatever_is": "порт %@ занят — закройте использующий его процесс (например, незавершённый codex login) и повторите",
        "quit": "Выход",
        "reading_usage_data": "Чтение данных об использовании…",
        "refresh_now": "Обновить сейчас",
        "remaining": "Осталось",
        "resets_in": "Сброс через %@ (%@)",
        "resets_on_at": "Сброс %@ в %@",
        "restore_default_order": "Восстановить порядок по умолчанию",
        "retry": "Повторить",
        "session": "Сессия",
        "session_5_h": "Сессия (5 ч)",
        "session_expired_sign_in_again": "сессия истекла — войдите снова",
        "settings": "Настройки",
        "settings_2": "Настройки…",
        "show_limits_as": "Показывать лимиты как",
        "sign_in_with": "Войти через %@",
        "connect_with": "Подключиться к %@",
        "sign_in_with_claude": "Войти через Claude…",
        "sign_in_with_openai": "Войти через OpenAI…",
        "sign_out": "Выйти",
        "signed_in_successfully": "Вход выполнен",
        "sonnet_week": "Sonnet · неделя",
        "spending_cap_reached": "достигнут потолок расходов",
        "spending_limit": "Лимит расходов",
        "the_session_is_stored_in_the": "Сессия хранится в собственном элементе связки ключей приложения. Приложение не читает учётные данные Claude Code, поэтому macOS не будет запрашивать доступ.",
        "today": "Сегодня",
        "todays_cost_total": "Стоимость за сегодня (всего)",
        "token_counts_come_from_local_codex": "Токены берутся из локальных сессий Codex CLI (~/.codex/sessions). Лимиты тарифа запрашиваются в реальном времени с chatgpt.com через вашу сессию OpenAI.",
        "unauthorized_sign_in_again": "сессия не авторизована — войдите снова",
        "unexpected_json": "Неожиданный JSON",
        "unlimited": "Безлимит",
        "updated_at": "Обновлено в %@",
        "usage_limit_reached": "достигнут лимит использования",
        "used": "Использовано",
        "used_2": "занято",
        "waiting_for_authorization": "Ожидание авторизации…",
        "waiting_for_browser_authorization": "Ожидание авторизации в браузере…",
        "week": "Неделя",
        "workspace_owner_credits_depleted": "кредиты владельца workspace исчерпаны",
        "workspace_usage_limit_reached": "достигнут лимит workspace",
        "you_can_close_this_tab_and": "Можно закрыть эту вкладку и вернуться в AI Usage.",
        "your_browser_will_open_to_authorize": "Откроется браузер для авторизации доступа с вашим аккаунтом Claude (тот же процесс, что и в Claude Code). После подтверждения приложение получит авторизацию автоматически.",
        "your_browser_will_open_to_authorize_2": "Откроется браузер для авторизации доступа с вашим аккаунтом OpenAI/ChatGPT (тот же процесс, что и в Codex CLI). После подтверждения приложение получит авторизацию автоматически.",
        "your_usage_limit_was_reached": "достигнут лимит вашего пользователя",
        "your_workspace_credits_are_depleted": "кредиты вашего пользователя в workspace исчерпаны",
    ]
}
